import {nodeWording} from '../dist/adoption.mjs';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {exerciseAccounts,alice,bob} from './accounts.test.mjs';
import {AccountError} from '../worker/account-policy.mjs';
import {exerciseComparisonThreads} from './comparison-threads.test.mjs';
import {exerciseElicitation} from './elicitation.test.mjs';
import {exerciseDiscussions} from './discussion.test.mjs';
import {exerciseDefinitions,exercisePhilosophy} from './definitions.test.mjs';
import {exerciseArguments} from './argument.test.mjs';
import {exerciseReasoning} from './reasoning.test.mjs';
import {exerciseReasoningDatabaseBoundary} from './reasoning-api.test.mjs';
import {exerciseAdoptionFulfillment,exerciseAdoptionDatabaseBoundary} from './adoption-fulfillment.test.mjs';
import {exercisePremiseDatabaseBoundary} from './premise-database.test.mjs';
import {exerciseReflectionDatabaseBoundary} from './reflection-database.test.mjs';
import {exerciseCounterpartIntegrity} from './counterpart-integrity.test.mjs';

const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); insert into auth.users(id) values('${alice.id}'),('${bob.id}');`);
await db.exec(await readFile('supabase/migrations/20260908233252_harmonious_accounts.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260910043435_allow_shared_comparison_judgments.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260910212254_overall_comparisons.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260910212326_argument_records.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260911094003_on_map_conversations.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260912045603_definitions_library.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260919032433_comparison_reasoning.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260919042425_adoption_fulfillment.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260919060236_existing_node_reasons.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260919062604_comparison_reflections.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260923002452_interaction_grammar_v4.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260929005321_counterpart_integrity.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20261009192043_philosophy_bank.sql','utf8'));
assert((await db.query("select prosecdef from pg_proc where proname in ('harmonious_snapshot','harmonious_commit')")).rows.every(row=>!row.prosecdef),'Application RPCs must not elevate the caller\'s privileges');
await db.exec('set role service_role');
const store={
  async snapshot(){return (await db.query('select public.harmonious_snapshot() as data')).rows[0].data;},
  async commit(actor,generation,changes){try{return (await db.query('select public.harmonious_commit($1::uuid,$2::bigint,$3::jsonb) as data',[actor,generation,JSON.stringify(changes)])).rows[0].data;}catch(e){const error=new AccountError(e.message,e.code==='PT409'?409:e.code==='PT403'?403:400);error.snapshotChanged=e.message==='snapshot_changed';throw error;}}
};
await exerciseAccounts(store);
await exerciseDiscussions(store);
await exerciseDefinitions(store);
await exerciseReasoning(store);
await exerciseReasoningDatabaseBoundary(store);
await exerciseCounterparts(store);
const adoptionFixtures=await exerciseAdoptionFulfillment(store);
await exerciseAdoptionDatabaseBoundary(store,adoptionFixtures);
await exercisePremiseDatabaseBoundary(store);
await exerciseReflectionDatabaseBoundary(store);
const definitionSnapshot=await store.snapshot(),definitionRecord=definitionSnapshot.records.find(r=>r.kind==='definition');
const forgedDefinition=structuredClone(definitionRecord.value);forgedDefinition.versions[0].body='Overwritten past';
await assert.rejects(()=>store.commit(definitionRecord.ownerId,definitionSnapshot.revision,[{kind:'definition',id:forgedDefinition.id,expectedRevision:definitionRecord.revision,value:forgedDefinition}]),/history cannot change/);
await assert.rejects(()=>store.commit(bob.id,definitionSnapshot.revision,[{kind:'definition',id:'forged-definition',expectedRevision:0,value:{...definitionRecord.value,id:'forged-definition',authorId:alice.id}}]),/Invalid definition author/);
assert.deepEqual(await store.snapshot(),definitionSnapshot,'Rejected library writes leave the database unchanged');
await exerciseElicitation(store);
await exerciseArguments(store);
const argumentSnapshot=await store.snapshot(),argumentEdge=argumentSnapshot.records.find(r=>r.kind==='argument_edge');
const invalidEndpoint=structuredClone(argumentEdge.value);invalidEndpoint.id='missing-endpoint-version';delete invalidEndpoint.from.version;
await assert.rejects(()=>store.commit(argumentEdge.ownerId,argumentSnapshot.revision,[{kind:'argument_edge',id:invalidEndpoint.id,expectedRevision:0,value:invalidEndpoint}]),/Invalid reasoning endpoint/);
const invalidAuthor={...argumentEdge.value,id:'forged-reasoning-author',authorId:argumentEdge.ownerId===alice.id?bob.id:alice.id};
await assert.rejects(()=>store.commit(argumentEdge.ownerId,argumentSnapshot.revision,[{kind:'argument_edge',id:invalidAuthor.id,expectedRevision:0,value:invalidAuthor}]),e=>e.status===403);
assert.deepEqual(await store.snapshot(),argumentSnapshot,'Rejected reasoning writes must leave the database unchanged');
const {thread}=await exerciseComparisonThreads(store);
const duplicate={...thread,id:'duplicate-parent'};
const duplicateSnapshot=await store.snapshot();
await assert.rejects(()=>store.commit(thread.createdBy,duplicateSnapshot.revision,[{kind:'comparison_thread',id:duplicate.id,value:duplicate,expectedRevision:0}]),e=>e.status===400);
const before=await store.snapshot(),owned=before.records.find(r=>r.kind==='map'&&r.ownerId===alice.id),other=before.records.find(r=>r.kind==='map'&&r.ownerId===bob.id);
await assert.rejects(()=>store.commit(alice.id,before.revision,[{kind:'map',id:owned.id,expectedRevision:owned.revision,value:{...owned.value,name:'Must roll back'}},{kind:'map',id:other.id,expectedRevision:other.revision,value:{...other.value,name:'Forbidden'}}]),e=>e.status===403);
assert.deepEqual(await store.snapshot(),before,'Partial batches must roll back');
await assert.rejects(()=>store.commit(alice.id,before.revision-1,[{kind:'map',id:owned.id,expectedRevision:owned.revision,value:owned.value}]),e=>e.snapshotChanged);
for(const role of ['anon','authenticated']){
  await db.exec(`set role ${role}`);
  await assert.rejects(()=>db.query('select * from public.harmonious_records'),e=>e.code==='42501');
  await assert.rejects(()=>db.query('select public.harmonious_snapshot()'),e=>e.code==='42501');
  await assert.rejects(()=>db.query('select public.harmonious_commit($1::uuid,0,\'[]\'::jsonb)',[alice.id]),e=>e.code==='42501');
  await db.exec('reset role');
}
await db.exec('set role service_role');assert((await store.snapshot()).records.length>0);await exerciseCounterpartIntegrity(store);await exercisePhilosophy(store);
const philosophySnapshot=await store.snapshot(),philosophyDefinition=philosophySnapshot.records.find(r=>r.kind==='definition'&&r.value.type==='principle');
await assert.rejects(()=>store.commit(alice.id,philosophySnapshot.revision,[{kind:'definition',id:'bad-philosophy-type',expectedRevision:0,value:{...philosophyDefinition.value,id:'bad-philosophy-type',type:'unsupported'}}]),/Invalid definition/);
const philosophyUse=philosophySnapshot.records.find(r=>r.kind==='discussion'&&r.value.history?.some(h=>h.definitionRefs?.some(ref=>ref.type==='principle'))).value,priorUse=philosophyUse.history[0],philosophyMap=philosophySnapshot.records.find(r=>r.kind==='map'&&r.id===philosophyUse.target.mapId).value,philosophyNode=philosophyMap.nodes.find(n=>n.id===philosophyUse.target.nodeId);
const philosophyPremise={mapId:philosophyMap.id,nodeId:philosophyNode.id,ideaId:philosophyNode.ideaId,ideaVersion:philosophyNode.ideaVersion,wording:nodeWording(philosophyMap,philosophyNode),contexts:[{id:philosophyUse.id,authorId:alice.id,version:priorUse.version,body:priorUse.body,definitionRefs:structuredClone(priorUse.definitionRefs)}]};
assert.equal((await db.query('select public.harmonious_valid_premise($1::jsonb,$2) as valid',[JSON.stringify(philosophyPremise),alice.id])).rows[0].valid,true);
philosophyPremise.contexts[0].definitionRefs[0].type='unsupported';assert.equal((await db.query('select public.harmonious_valid_premise($1::jsonb,$2) as valid',[JSON.stringify(philosophyPremise),alice.id])).rows[0].valid,false);
assert.deepEqual(await store.snapshot(),philosophySnapshot,'Rejected philosophy writes leave all records unchanged');await db.exec('reset role');
await db.close();console.log('PostgreSQL migration, two-account persistence, atomic rollback, revision conflicts, and database access boundaries passed.');
import {exerciseCounterparts} from './counterparts.test.mjs';
