import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {alice,bob,memoryStore,seedActor,edit,view,addNode} from './accounts.test.mjs';
import {startAccountComparison,saveAccountChanges,handleAccountAPI,ADOPTION_CAPABILITY,REASONING_CAPABILITY} from '../worker/account-api.mjs';
import {validateAccountChanges} from '../worker/account-policy.mjs';
import {makeDiscussion} from '../dist/discussion.mjs';
import {makeDefinition,definitionReference,definitionReferenceText} from '../dist/definitions.mjs';
import {adoptionPreview,prepareAdoption,adoptionState,adoptionFulfillmentId} from '../dist/adoption-fulfillment.mjs';
import {accountKey,accountClone,ownedAccountRecords,accountChanges} from '../dist/account-model.mjs';
import {synchronizeIdeas} from '../dist/adoption.mjs';
import {validateWorkspace} from '../dist/workspace.mjs';
import {counterpartLinkProblem} from '../dist/counterparts.mjs';

async function commitPrepared(store,actor,result){const baseline=await view(store,actor),changes=accountChanges(ownedAccountRecords(result.workspace,actor.id,baseline.ownedKeys),new Map(ownedAccountRecords(baseline.workspace,actor.id,baseline.ownedKeys).map(r=>[accountKey(r.kind,r.id),accountClone(r.value)])),baseline.revisions);await saveAccountChanges(store,actor.id,changes);return changes;}
const preparedChanges=(baseline,workspace,actor)=>accountChanges(ownedAccountRecords(workspace,actor.id,baseline.ownedKeys),new Map(ownedAccountRecords(baseline.workspace,actor.id,baseline.ownedKeys).map(r=>[accountKey(r.kind,r.id),accountClone(r.value)])),baseline.revisions);
export async function exerciseAdoptionFulfillment(store){
  for(const actor of [alice,bob])await edit(store,actor,ws=>{ws.maps.find(m=>m.ownerId===actor.id).visibility='shared';addNode(ws,actor,'Adoption claim '+actor.name);});
  let ws=(await view(store,alice)).workspace;const a=ws.maps.find(m=>m.ownerId===alice.id),b=ws.maps.find(m=>m.ownerId===bob.id),target={type:'node',mapId:a.id,nodeId:a.nodes.at(-1).id};
  const {comparisonThread:thread}=await startAccountComparison(store,alice.id,{aMapId:a.id,bMapId:b.id});let definition,suggestion;
  await edit(store,alice,w=>{definition=makeDefinition(w,{type:'definition',title:'Shared meaning',body:'This exact meaning was invoked.'},alice.id);w.definitions.push(definition);const refs=[definitionReference(definition)];w.discussions.push(makeDiscussion(w,{kind:'context',action:'context',target,body:definitionReferenceText(refs),definitionRefs:refs},alice.id));suggestion=makeDiscussion(w,{comparisonId:thread.id,kind:'adoption',action:'adoption',target,body:'Consider this node.'},alice.id);w.discussions.push(suggestion);});
  await edit(store,alice,w=>{const old=w.definitions.find(d=>d.id===definition.id);w.definitions=w.definitions.map(d=>d.id===old.id?makeDefinition(w,{title:'Private later version',body:'Do not copy this uninvoked wording.'},alice.id,old):d);});
  ws=(await view(store,bob)).workspace;const preview=adoptionPreview(ws,suggestion.id,bob.id),original=structuredClone(ws),parent=preview.destinationMap.nodes.find(n=>n.parent===null&&n.id!==preview.sourceSnapshot.wording.frame);
  assert.equal(preview.definitions.length,1);assert(!JSON.stringify(preview).includes('Do not copy this uninvoked wording.'));
  await assert.rejects(()=>prepareAdoption(ws,{suggestionId:suggestion.id,reviewedSource:preview.sourceSnapshot,mode:'copy',parentId:parent.id},alice.id),/other map owner/);
  const draft={suggestionId:suggestion.id,reviewedSource:preview.sourceSnapshot,mode:'copy',parentId:parent.id,title:'My independent wording',summary:'My explanation',definitionKeys:preview.definitions.map(d=>d.key),linkCounterpart:false};
  const prepared=await prepareAdoption(ws,draft,bob.id);assert.deepEqual(ws,original,'Preparation cannot mutate the working workspace');assert.equal(prepared.receipt.id,await adoptionFulfillmentId(suggestion.id,bob.id));assert.equal(prepared.node.parent,parent.id);assert.notEqual(prepared.node.ideaId,preview.sourceNode.ideaId);assert.deepEqual(prepared.node.copiedFrom,{ideaId:preview.sourceNode.ideaId,version:preview.sourceNode.ideaVersion,mapId:a.id,nodeId:target.nodeId});
  assert.equal(prepared.workspace.endorsements.length,ws.endorsements.length);assert.equal(prepared.workspace.discussions.filter(r=>r.kind==='relationship').length,ws.discussions.filter(r=>r.kind==='relationship').length);assert.equal(prepared.receipt.adoption.counterpartId,null);
  assert.deepEqual(prepared.workspace.maps.find(m=>m.id===a.id),ws.maps.find(m=>m.id===a.id));const imported=prepared.workspace.definitions.find(d=>d.id===prepared.receipt.adoption.importedDefinitions[0].definitionId);assert.equal(imported.authorId,bob.id);assert.equal(imported.copiedFrom.authorId,alice.id);assert.equal(imported.versions[0].body,'This exact meaning was invoked.');assert.equal(prepared.workspace.discussions.find(r=>r.id===prepared.receipt.adoption.contextId).authorId,bob.id);
  const forgedChanges=preparedChanges(await view(store,bob),prepared.workspace,bob),forgedReceipt=forgedChanges.find(c=>c.id===prepared.receipt.id),beforeForged=await store.snapshot();forgedReceipt.id='adoption-result-'+'f'.repeat(64);forgedReceipt.value.id=forgedReceipt.id;
  await assert.rejects(()=>saveAccountChanges(store,bob.id,forgedChanges),/Invalid adoption fulfillment identity/);assert.deepEqual(await store.snapshot(),beforeForged,'The Worker rejects a fabricated digest before any mutation');
  const changes=await commitPrepared(store,bob,prepared),saved=await store.snapshot(),replay=await saveAccountChanges(store,bob.id,changes);assert(replay.replayed);assert.deepEqual(await store.snapshot(),saved,'A lost-response retry creates no extra node or revision');
  const env={APP_ORIGIN:'https://harmonious.example',SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public-test',SUPABASE_SECRET_KEY:'server-test',BETA_INVITE_EMAILS:'alice@example.test,bob@example.test'};
  const api=async(capabilities,body)=>handleAccountAPI(new Request(env.APP_ORIGIN+'/api/workspace',{method:body?'PUT':'GET',headers:{origin:env.APP_ORIGIN,'X-Harmonious-Capabilities':capabilities,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}),env,{store,auth:{identify:async()=>({actor:bob,cookies:[]})}});
  let response=await api(REASONING_CAPABILITY);assert.equal(response.status,409);assert.equal((await response.json()).requiredCapability,ADOPTION_CAPABILITY);response=await api(REASONING_CAPABILITY,{changes});assert.equal(response.status,409);assert.deepEqual(await store.snapshot(),saved);response=await api(REASONING_CAPABILITY+','+ADOPTION_CAPABILITY);assert.equal(response.status,200);assert.equal((await response.json()).workspace.schemaVersion,4);
  const reopened=(await view(store,bob)).workspace;assert.equal((await prepareAdoption(reopened,draft,bob.id)).reused,true);assert.equal(adoptionState(reopened,reopened.discussions.find(r=>r.id===suggestion.id)).label,'Added to my map');
  await assert.rejects(()=>edit(store,bob,w=>{const old=w.discussions.find(r=>r.id===prepared.receipt.id);w.discussions=w.discussions.map(r=>r.id===old.id?makeDiscussion(w,{...old,status:'withdrawn'},bob.id,old):r);}),/immutable|cannot be edited/);
  const portable=structuredClone(reopened);const authored=structuredClone(portable.discussions);portable.schemaVersion=3;validateWorkspace(portable);assert.equal(portable.schemaVersion,6);assert.deepEqual(portable.discussions,authored);
  let existingSuggestion,secondSuggestion;
  await edit(store,alice,w=>{existingSuggestion=makeDiscussion(w,{comparisonId:thread.id,kind:'adoption',action:'adoption',target},alice.id);w.discussions.push(existingSuggestion);secondSuggestion=makeDiscussion(w,{comparisonId:thread.id,kind:'adoption',action:'adoption',target},alice.id);w.discussions.push(secondSuggestion);});
  ws=(await view(store,bob)).workspace;let p=adoptionPreview(ws,existingSuggestion.id,bob.id),chosen=p.destinationMap.nodes.find(n=>n.parent!==null&&n.id!==prepared.node.id&&!counterpartLinkProblem(ws,thread.id,target,{type:'node',mapId:p.destinationMap.id,nodeId:n.id}));const existing=await prepareAdoption(ws,{suggestionId:existingSuggestion.id,reviewedSource:p.sourceSnapshot,mode:'existing',nodeId:chosen.id,linkCounterpart:true},bob.id);assert.deepEqual(existing.workspace.maps,ws.maps);assert.deepEqual(existing.workspace.definitions,ws.definitions);assert.equal(existing.receipt.adoption.importedDefinitions.length,0);assert(existing.receipt.adoption.counterpartId);await commitPrepared(store,bob,existing);
  ws=(await view(store,bob)).workspace;p=adoptionPreview(ws,secondSuggestion.id,bob.id);const defer=await prepareAdoption(ws,{suggestionId:secondSuggestion.id,reviewedSource:p.sourceSnapshot,mode:'not_now'},bob.id);await commitPrepared(store,bob,defer);ws=(await view(store,bob)).workspace;assert.equal(adoptionState(ws,ws.discussions.find(r=>r.id===secondSuggestion.id)).label,'Not now');p=adoptionPreview(ws,secondSuggestion.id,bob.id);
  await assert.rejects(()=>prepareAdoption(ws,{...draft,suggestionId:secondSuggestion.id,reviewedSource:p.sourceSnapshot,definitionKeys:p.definitions.map(d=>d.key),linkCounterpart:true},bob.id),/same frame/,'Copying into another frame must not add a cross-frame counterpart');
  const later=await prepareAdoption(ws,{...draft,suggestionId:secondSuggestion.id,reviewedSource:p.sourceSnapshot,definitionKeys:p.definitions.map(d=>d.key),linkCounterpart:false},bob.id);assert.equal(later.receipt.adoption.importedDefinitions[0].definitionId,imported.id,'An exact previous import is reused');await commitPrepared(store,bob,later);
  let staleSuggestion;await edit(store,alice,w=>{staleSuggestion=makeDiscussion(w,{comparisonId:thread.id,kind:'adoption',action:'adoption',target},alice.id);w.discussions.push(staleSuggestion);});ws=(await view(store,bob)).workspace;p=adoptionPreview(ws,staleSuggestion.id,bob.id);const stale=await prepareAdoption(ws,{...draft,suggestionId:staleSuggestion.id,reviewedSource:p.sourceSnapshot,definitionKeys:[]},bob.id);
  await edit(store,alice,w=>{const map=w.maps.find(m=>m.id===a.id);map.nodes.find(n=>n.id===target.nodeId).summary='Source changed during preview';map.revision++;synchronizeIdeas(w,map);});const beforeRejected=await store.snapshot();await assert.rejects(()=>commitPrepared(store,bob,stale),/source changed/i);assert.deepEqual(await store.snapshot(),beforeRejected);
  ws=(await view(store,bob)).workspace;await assert.rejects(()=>prepareAdoption(ws,{...draft,suggestionId:staleSuggestion.id,reviewedSource:p.sourceSnapshot},bob.id),/source changed/i);
  await edit(store,alice,w=>{const old=w.discussions.find(r=>r.id===staleSuggestion.id);w.discussions=w.discussions.map(r=>r.id===old.id?makeDiscussion(w,{...old,status:'withdrawn'},alice.id,old):r);});ws=(await view(store,bob)).workspace;p=adoptionPreview(ws,staleSuggestion.id,bob.id);await assert.rejects(()=>prepareAdoption(ws,{...draft,suggestionId:staleSuggestion.id,reviewedSource:p.sourceSnapshot},bob.id),/withdrawn/);
  await assert.rejects(()=>prepareAdoption(ws,{suggestionId:staleSuggestion.id,reviewedSource:p.sourceSnapshot,mode:'not_now'},bob.id),/withdrawn/);
  assert.throws(()=>makeDiscussion(ws,{comparisonId:thread.id,kind:'reply',action:'adoption_not_now',target:{type:'entry',entryId:staleSuggestion.id},layer:'inquiries',body:'Forged late Not now'},bob.id),/withdrawn|available/,'The raw model also rejects Not now on a withdrawn suggestion');
  await edit(store,bob,w=>{const map=w.maps.find(m=>m.id===b.id);map.nodes.find(n=>n.id===prepared.node.id).title='My later change';map.revision++;synchronizeIdeas(w,map);});ws=(await view(store,bob)).workspace;assert(adoptionState(ws,ws.discussions.find(r=>r.id===suggestion.id)).changed);
  await edit(store,alice,w=>{w.maps.find(m=>m.id===a.id).visibility='private';});ws=(await view(store,bob)).workspace;assert(!ws.discussions.some(r=>r.id===suggestion.id));assert(ws.maps.find(m=>m.id===b.id).nodes.some(n=>n.id===prepared.node.id));assert.equal(ws.definitions.find(d=>d.id===imported.id).copiedFrom.body,'This exact meaning was invoked.');assert(!JSON.stringify(ws).includes('Do not copy this uninvoked wording.'));
  await edit(store,alice,w=>{w.maps.find(m=>m.id===a.id).visibility='shared';});
  await edit(store,bob,w=>{const map=w.maps.find(m=>m.id===b.id);map.nodes=map.nodes.filter(n=>n.id!==prepared.node.id);map.revision++;});ws=(await view(store,bob)).workspace;assert(adoptionState(ws,ws.discussions.find(r=>r.id===suggestion.id)).removed);assert.equal((await prepareAdoption(ws,draft,bob.id)).reused,true,'Deleting the copy does not reopen fulfillment or create duplicates');
  let reverseSuggestion;await edit(store,bob,w=>{reverseSuggestion=makeDiscussion(w,{comparisonId:thread.id,kind:'adoption',action:'adoption',target:{type:'node',mapId:b.id,nodeId:chosen.id}},bob.id);w.discussions.push(reverseSuggestion);});ws=(await view(store,alice)).workspace;p=adoptionPreview(ws,reverseSuggestion.id,alice.id);const reverse=await prepareAdoption(ws,{suggestionId:reverseSuggestion.id,reviewedSource:p.sourceSnapshot,mode:'copy',parentId:p.destinationMap.nodes.find(n=>n.parent===null).id},alice.id);await commitPrepared(store,alice,reverse);assert.equal(reverse.receipt.authorId,alice.id);
  console.log('Recipient adoption copy/existing/defer, exact provenance and definition imports, atomic retries, source changes, receipts and privacy passed.');
  return {suggestion,prepared,thread,a,b,definition};
}

export async function exerciseAdoptionDatabaseBoundary(store,fixtures){
  let suggestion;await edit(store,alice,w=>{suggestion=makeDiscussion(w,{comparisonId:fixtures.thread.id,kind:'adoption',action:'adoption',target:fixtures.suggestion.target},alice.id);w.discussions.push(suggestion);});
  let numbered;await edit(store,alice,w=>{numbered=makeDefinition(w,{type:'standard',title:'Numbered standard',body:'Version 1'},alice.id);w.definitions.push(numbered);});
  for(let version=2;version<=10;version++)await edit(store,alice,w=>{const old=w.definitions.find(d=>d.id===numbered.id);numbered=makeDefinition(w,{title:'Numbered standard',body:'Version '+version},alice.id,old);w.definitions=w.definitions.map(d=>d.id===old.id?numbered:d);});
  for(const version of [2,10])await edit(store,alice,w=>{const refs=[definitionReference(numbered,version)];w.discussions.push(makeDiscussion(w,{kind:'context',action:'context',target:fixtures.suggestion.target,body:definitionReferenceText(refs),definitionRefs:refs},alice.id));});
  const orderedSuffixes=['$','Z','_','z','é','\uE000','\u{10000}'],orderingDefinitions=[];
  await edit(store,alice,w=>{for(const suffix of [...orderedSuffixes].reverse()){const d=makeDefinition(w,{type:'definition',title:'Portable identifier '+suffix,body:'Pinned imported identifier '+suffix},alice.id);d.id='ordering-'+suffix;w.definitions.push(d);orderingDefinitions.push(d);}});
  for(const suffix of ['\u{10000}','\uE000'])await edit(store,alice,w=>{const refs=orderingDefinitions.map(d=>definitionReference(d)),context=makeDiscussion(w,{kind:'context',action:'context',target:fixtures.suggestion.target,body:definitionReferenceText(refs),definitionRefs:refs},alice.id);context.id='context-order-'+suffix;w.discussions.push(context);});
  const baseline=await view(store,bob),preview=adoptionPreview(baseline.workspace,suggestion.id,bob.id),parent=preview.destinationMap.nodes.find(n=>n.parent===null),staged=await prepareAdoption(baseline.workspace,{suggestionId:suggestion.id,reviewedSource:preview.sourceSnapshot,mode:'copy',parentId:parent.id,definitionKeys:preview.definitions.map(d=>d.key)},bob.id),changes=preparedChanges(baseline,staged.workspace,bob),before=await store.snapshot();
  assert.deepEqual(preview.sourceSnapshot.definitions.filter(ref=>ref.definitionId===numbered.id).map(ref=>ref.version),[10,2],'Definition snapshots use the same lexical version order in JS and SQL');
  assert.deepEqual(preview.sourceSnapshot.definitions.filter(ref=>ref.definitionId.startsWith('ordering-')).map(ref=>ref.definitionId),orderedSuffixes.map(suffix=>'ordering-'+suffix),'Portable punctuation and Unicode identifiers sort by UTF-8 bytes, independent of locale or UTF-16 ordering');
  assert.deepEqual(preview.sourceSnapshot.contexts.filter(c=>c.id.startsWith('context-order-')).map(c=>c.id),['context-order-\uE000','context-order-\u{10000}'],'Source context ordering also matches database C collation');
  const receiptChange=batch=>batch.find(c=>c.id===staged.receipt.id),reject=async(mutator,pattern)=>{const batch=structuredClone(changes);mutator(batch);await assert.rejects(()=>store.commit(bob.id,before.revision,batch),pattern);assert.deepEqual(await store.snapshot(),before,'A rejected adoption rolls back map, idea, context and receipt together');};
  await reject(batch=>{const r=receiptChange(batch);r.id='adoption-result-'+'f'.repeat(64);r.value.id=r.id;},/Invalid immutable adoption receipt/);
  await reject(batch=>{receiptChange(batch).value.adoption.source.mapRevision++;},/source changed/);
  await reject(batch=>{receiptChange(batch).value.adoption.destination.mapId=fixtures.a.id;},/Invalid immutable adoption receipt/);
  await reject(batch=>{receiptChange(batch).value.adoption.source.definitions.push({definitionId:'private-uninvoked',authorId:alice.id,type:'definition',version:99,title:'Secret',body:'Not shared'});},/source changed/);
  await reject(batch=>{const item=receiptChange(batch).value.adoption.importedDefinitions[0];item.source.body='Forged meaning';const definition=batch.find(c=>c.kind==='definition'&&c.id===item.definitionId);if(definition)definition.value.copiedFrom.body='Forged meaning';},/invoked source definitions/);
  await assert.rejects(()=>store.commit(bob.id,before.revision,[receiptChange(changes)]),/destination changed or unavailable/);assert.deepEqual(await store.snapshot(),before);
  const foreign=structuredClone(receiptChange(changes));foreign.value.authorId=alice.id;await assert.rejects(()=>store.commit(alice.id,before.revision,[foreign]),/other map owner/);assert.deepEqual(await store.snapshot(),before);
  const existingNode=preview.destinationMap.nodes.find(n=>n.parent!==null),existing=await prepareAdoption(baseline.workspace,{suggestionId:suggestion.id,reviewedSource:preview.sourceSnapshot,mode:'existing',nodeId:existingNode.id},bob.id),existingChanges=preparedChanges(baseline,existing.workspace,bob),editedMap=structuredClone(preview.destinationMap);editedMap.name='Must not rename while using existing node';
  await assert.rejects(()=>store.commit(bob.id,before.revision,[{kind:'map',id:editedMap.id,expectedRevision:baseline.revisions[accountKey('map',editedMap.id)],value:editedMap},...existingChanges]),/existing node cannot alter its map/);assert.deepEqual(await store.snapshot(),before);
  const fabricated=makeDefinition(baseline.workspace,{type:'definition',title:'Pretend',body:'Pretend original',copiedFrom:{definitionId:'private-source',authorId:alice.id,type:'definition',version:1,title:'Pretend',body:'Pretend original'}},bob.id);
  await assert.rejects(()=>store.commit(bob.id,before.revision,[{kind:'definition',id:fabricated.id,expectedRevision:0,value:fabricated}]),/through an adoption receipt/);assert.deepEqual(await store.snapshot(),before);
  await store.commit(bob.id,before.revision,changes);const saved=await store.snapshot(),receipt=saved.records.find(r=>r.id===staged.receipt.id);
  await assert.rejects(()=>store.commit(bob.id,saved.revision,[{kind:'discussion',id:receipt.id,expectedRevision:receipt.revision,value:{...receipt.value,status:'withdrawn'}}]),/receipts cannot be edited or withdrawn/);assert.deepEqual(await store.snapshot(),saved);
  const duplicate=structuredClone(receipt.value);duplicate.id='adoption-result-'+'e'.repeat(64);await assert.rejects(()=>store.commit(bob.id,saved.revision,[{kind:'discussion',id:duplicate.id,expectedRevision:0,value:duplicate}]),/already fulfilled/);assert.deepEqual(await store.snapshot(),saved);
  console.log('Direct database adoption identity, recipient permissions, source review, independent node, imported definition and atomic rollback guards passed.');
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const store=memoryStore();for(const actor of [alice,bob])await seedActor(store,actor);await exerciseAdoptionFulfillment(store);}
