import assert from 'node:assert/strict';
import {initialWorkspace,recordComparison,comparisonConsensus,comparisonPairKey} from '../dist/workspace.mjs';
import {WorkspaceController} from '../dist/workspace-ui.mjs';
import {AccountWorkspace} from '../dist/account-ui.mjs';

const workspace=initialWorkspace(),[a,b]=workspace.maps;
const input={aMapId:a.id,bMapId:b.id,aNodeId:'a1',bNodeId:'a1',questionStatus:'matched',answerStatus:'aligned',question:'Where should we start?',notes:'First person’s reasoning'};
const first=recordComparison(workspace,input,null,a.ownerId);
const shared=recordComparison(workspace,{...input,notes:'Second person’s reasoning'},first,b.ownerId);
workspace.comparisons=[shared];
const legacy=structuredClone(shared);
for(const judgment of legacy.judgments){delete judgment.aSnapshot;delete judgment.bSnapshot;}
assert.equal(comparisonConsensus(workspace,legacy).state,'review','Legacy shared judgments must be reviewed before claiming agreement');
const sameOwnerWorkspace=structuredClone(workspace);sameOwnerWorkspace.maps[1].ownerId=a.ownerId;
const single=recordComparison(sameOwnerWorkspace,input,null,a.ownerId);
assert.equal(comparisonConsensus(sameOwnerWorkspace,single).label,'Your comparison');

const element=()=>({value:'',textContent:'',dataset:{},children:[],querySelectorAll(){return ['question-status','shared-question','answer-status','comparison-notes','elicitation-response','divergence-confirmation'].map(id=>document.getElementById(id));},append(...children){this.children.push(...children);},replaceChildren(...children){this.children=children;}});
const elements=new Map();
globalThis.document={getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id);},createElement:element,body:{classList:{remove(){}}}};
const controller={workspace,account:{actor:{id:b.ownerId}},editingRecord:shared.id,activeMapId:b.id,comparisonDirty:false,mode:'compare',activeMap(){return this.workspace.maps.find(map=>map.id===this.activeMapId);},loadComparisonForm:WorkspaceController.prototype.loadComparisonForm,renderElicitation:WorkspaceController.prototype.renderElicitation,populateMaps(){},renderComparison(){},participation:{refresh(){}}};
controller.loadComparisonForm(shared);
assert.equal(elements.get('comparison-notes').value,'Second person’s reasoning');
const textOf=node=>[node.textContent,...node.children.map(textOf)].join('\n');
const history=textOf(elements.get('comparison-snapshot-content'));
assert(history.includes('First person’s reasoning')&&history.includes('Second person’s reasoning'),'Review must expose both people’s reasoning');
const updatedWorkspace=structuredClone(workspace);
updatedWorkspace.comparisons=[recordComparison(updatedWorkspace,{...input,notes:'Updated on another device'},shared,b.ownerId)];
const account={controller,actor:{id:b.ownerId},renderAccountName:AccountWorkspace.prototype.renderAccountName};
AccountWorkspace.prototype.accept.call(account,{workspace:updatedWorkspace,revisions:{},ownedKeys:[],actor:account.actor});
assert.equal(elements.get('comparison-notes').value,'Updated on another device','A clean open form must refresh with the saved judgment');
assert.equal(controller.editingRecord,shared.id,'Refreshing preserves the selected proposal');
const clarificationA=recordComparison(workspace,{...input,answerStatus:'divergent',elicitationResponse:'A explains the position'},null,a.ownerId);
const clarificationB=recordComparison(workspace,{...input,answerStatus:'divergent',elicitationResponse:'B answers the proposed question'},clarificationA,b.ownerId);
controller.workspace={...workspace,comparisons:[clarificationB]};controller.loadComparisonForm(clarificationB);
assert.equal(elements.get('elicitation-response').value,'B answers the proposed question');
assert.equal(elements.get('elicitation-status').textContent,'Responses ready for both people to review');
assert(elements.get('divergence-confirmation').disabled,'Earlier confirmation is historical, not an active authoring choice');
assert(elements.get('record-comparison').hidden);
assert(elements.get('comparison-notes').disabled);
assert(textOf(elements.get('elicitation-responses')).includes('A explains the position'));
elements.get('shared-question').value='A different question';controller.renderElicitation(clarificationB);
assert(elements.get('divergence-confirmation').disabled,'A changed question cannot retain a confirmation');
const browserController={...controller,argument:{canLeave:()=>true,reset(){}}, workspace:structuredClone(workspace),activeComparisonPair:null,recordsForActivePair:WorkspaceController.prototype.recordsForActivePair,mapName:WorkspaceController.prototype.mapName,renderRecords:WorkspaceController.prototype.renderRecords,openComparisonPair:WorkspaceController.prototype.openComparisonPair,setComparisonRoute:WorkspaceController.prototype.setComparisonRoute,canLeaveComparison:()=>true,clearComparison(){this.editingRecord=null;},ready:true,showMode:()=>true};
browserController.workspace.comparisons=[];
globalThis.location={pathname:'/',search:'',hash:''};
globalThis.history={replaceState(state,title,url){location.hash=url.includes('#')?url.slice(url.indexOf('#')):'';}};
browserController.renderRecords();
assert.equal(elements.get('comparison-records').children.length,1,'The main list includes an empty saved comparison');
assert(textOf(elements.get('comparison-records')).includes('Ready to begin'));
elements.get('comparison-records').children[0].onclick();
assert.equal(browserController.activeComparisonPair,comparisonPairKey(workspace.comparisonThreads[0]));
browserController.renderRecords();
assert(textOf(elements.get('comparison-records')).includes('No judgments yet'));
const thread=workspace.comparisonThreads[0];
assert.equal(new URLSearchParams(location.hash.slice(1)).get('comparison'),thread.id);
browserController.activeComparisonPair=null;
WorkspaceController.prototype.openComparisonRoute.call(browserController);
assert.equal(browserController.activeComparisonPair,comparisonPairKey(thread),'A direct link reopens an empty comparison');
browserController.workspace=workspace;let openedProposal;
browserController.openRecord=id=>{openedProposal=id;};
browserController.setComparisonRoute(thread.id,shared.id);
WorkspaceController.prototype.openComparisonRoute.call(browserController);
assert.equal(openedProposal,shared.id,'A proposal link drills into its own parent');
console.log('Comparison review shows both people, requires legacy source review, and refreshes clean forms.');
