import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {alice,bob,memoryStore,seedActor,edit,addNode,view} from './accounts.test.mjs';
import {validateAccountChanges} from '../worker/account-policy.mjs';
import {startAccountComparison} from '../worker/account-api.mjs';
import {createOwnedMap,synchronizeIdeas} from '../dist/adoption.mjs';
import {makeDiscussion} from '../dist/discussion.mjs';

// Real browser interactions against the real account projection and write policy,
// using two isolated browser contexts and an in-memory database, never live data.
const playwright=process.env.HARMONIOUS_PLAYWRIGHT;
if(!playwright)throw Error('Set HARMONIOUS_PLAYWRIGHT to the installed playwright entry point.');
const {chromium}=await import(pathToFileURL(playwright));
const store=memoryStore();for(const actor of [alice,bob]){await seedActor(store,actor);await edit(store,actor,ws=>{const map=ws.maps.find(m=>m.ownerId===actor.id);map.name=actor.name+' worldview';map.visibility='shared';const n=addNode(ws,actor,actor.name+' position');map.relations.push({id:'illustration-'+actor.name,from:n.id,to:n.parent,type:'illustrative',note:''});if(actor===alice)addNode(ws,actor,'Alice extra');});}
const aData=await view(store,alice),aMap=aData.workspace.maps.find(m=>m.ownerId===alice.id),bMap=aData.workspace.maps.find(m=>m.ownerId===bob.id);
let loseNextAcknowledgment=false;
const server=createServer(async(req,res)=>{
  try{
    const url=new URL(req.url,'http://localhost'),actor=req.headers['x-test-actor']==='bob'?bob:alice;
    if(url.pathname.startsWith('/api/')){
      res.setHeader('content-type','application/json');let result;let body='';for await(const chunk of req)body+=chunk;const input=body?JSON.parse(body):null;
      if(url.pathname==='/api/session')result={configured:true,actor,signup:{mode:'public'}};
      else if(url.pathname==='/api/comparisons')result=await startAccountComparison(store,actor.id,input);
      else if(url.pathname==='/api/workspace'&&req.method==='PUT'){const snapshot=await store.snapshot(),accepted=validateAccountChanges(snapshot,actor.id,input.changes);result=await store.commit(actor.id,snapshot.revision,accepted);if(loseNextAcknowledgment){loseNextAcknowledgment=false;throw Error('The acknowledgment was lost. Retry your choice.');}}
      else result={...await view(store,actor),actor};
      res.end(JSON.stringify(result));return;
    }
    const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!/^[a-z0-9.-]+$/.test(name)){res.writeHead(404);res.end();return;}
    let content=await readFile(resolve('dist',name),'utf8');if(name==='index.html')content=content.replace('src="./app.mjs"','src="./beta-boot.mjs"').replace('</head>','<link rel="stylesheet" href="./accounts.css"></head>');
    res.setHeader('content-type',name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'text/javascript');res.end(content);
  }catch(error){res.writeHead(error.status||500,{'content-type':'application/json'});res.end(JSON.stringify({error:error.message}));}
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,channel:process.env.HARMONIOUS_BROWSER||'msedge'});const errors=[];
try{
  await mkdir('build/design-review',{recursive:true});
  const ac=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',extraHTTPHeaders:{'x-test-actor':'alice'}}),bc=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',extraHTTPHeaders:{'x-test-actor':'bob'}});
  const a=await ac.newPage(),b=await bc.newPage();for(const page of [a,b])page.on('pageerror',e=>errors.push(e.message));
  const saved=p=>p.waitForFunction(()=>document.getElementById('storage-status')?.textContent.includes('All changes saved'));
  const pop=p=>p.locator('.discussion-popover'),action=(p,name)=>pop(p).getByRole('button',{name,exact:true}).click();
  const expand=async p=>{await p.locator('.comparison-view-options>summary').click();await p.locator('#compare-all-a').click();await p.locator('#compare-all-b').click();await p.locator('.comparison-view-options>summary').click();await p.getByRole('button',{name:'Fit both maps',exact:true}).click();};
  const node=(p,name)=>p.locator('#compare-canvas .node-main').filter({has:p.getByText(name,{exact:true})}).click();
  const cp=(p,name)=>p.locator(`.counterpart-placeholder[data-source-label="${name}"]`);
  await a.goto(origin);await a.getByRole('button',{name:'Create comparison',exact:true}).click();await a.locator('#compare-map-a').selectOption(aMap.id);await a.locator('#compare-map-b').selectOption(bMap.id);await a.locator('#start-comparison').click();await a.locator('#workspace-message').filter({hasText:'Comparison saved'}).waitFor();const url=a.url();await expand(a);
  const aliceBefore=structuredClone((await view(store,alice)).workspace.maps.find(m=>m.id===aMap.id));
  assert.equal(await a.locator('.counterpart-placeholder').count(),3,'Each ordinary node starts independently with a ghost; frame headings do not');
  const initialSnapshot=JSON.stringify((await view(store,alice)).workspace),initialCamera=await a.locator('#compare-canvas .comparison-world').evaluate(el=>el.style.transform);
  await cp(a,'Alice position').getByRole('button',{name:'Link counterpart',exact:true}).focus();await a.keyboard.press('Enter');assert.equal(await a.locator('#counterpart-node').inputValue(),'');await a.keyboard.press('Escape');
  assert(await cp(a,'Alice position').getByRole('button',{name:'Link counterpart',exact:true}).evaluate(el=>el===document.activeElement),'Escape returns focus to the rebuilt initiating ghost');assert.equal(await a.locator('#compare-canvas .comparison-world').evaluate(el=>el.style.transform),initialCamera);assert.equal(JSON.stringify((await view(store,alice)).workspace),initialSnapshot,'Opening or cancelling a ghost writes no map, request, link or layout record');
  await node(a,'Alice position');assert.equal(await cp(a,'Alice position').count(),1);assert.match(await pop(a).innerText(),/No counterpart linked/);
  await action(a,'Request counterpart');assert.equal(await cp(a,'Alice position').count(),1,'Opening a request keeps the existing unlinked ghost');assert.match(await cp(a,'Alice position').innerText(),/No counterpart linked/);await action(a,'Close');await node(a,'Alice position');await action(a,'Request counterpart');await action(a,'Send request');await saved(a);await action(a,'Close');
  assert.equal(await cp(a,'Alice position').count(),1);assert.match(await cp(a,'Alice position').innerText(),/Counterpart requested/);await a.getByRole('button',{name:'Fit both maps',exact:true}).click();await a.screenshot({path:'build/design-review/counterpart-requested.png',fullPage:true});
  await b.goto(url);await expand(b);assert.equal(await cp(b,'Alice position').count(),1,'Saved request retains its spot for the second account');
  await cp(b,'Alice position').getByRole('button',{name:'Respond',exact:true}).click();await action(b,'Create counterpart in my map');await b.locator('#counterpart-node').selectOption('status');await b.locator('#counterpart-title').fill('Bob response');await b.locator('#counterpart-summary').fill('My independently authored counterpart.');
  b.once('dialog',d=>d.dismiss());await action(b,'Close');assert.equal(await b.locator('#counterpart-title').inputValue(),'Bob response','Declining discard preserves counterpart draft');
  const initiatingBefore=await b.getByRole('button',{name:'Select Alice position from Alice worldview by Alice',exact:true}).boundingBox(),linkingZoom=await b.locator('#compare-canvas .comparison-zoom').innerText();
  await action(b,'Create and link counterpart');await saved(b);assert.match(await pop(b).innerText(),/Agreement has not been judged/);await action(b,'Close');
  const initiatingAfter=await b.getByRole('button',{name:'Select Alice position from Alice worldview by Alice',exact:true}).boundingBox();assert(Math.abs(initiatingAfter.x-initiatingBefore.x)<1&&Math.abs(initiatingAfter.y-initiatingBefore.y)<1,'Link completion anchors its initiating real node');assert.equal(await b.locator('#compare-canvas .comparison-zoom').innerText(),linkingZoom,'Link completion preserves zoom');
  let ws=(await view(store,bob)).workspace;const created=ws.maps.find(m=>m.id===bMap.id).nodes.find(n=>n.title==='Bob response');assert(created);assert.equal(created.parent,'status');assert.deepEqual(ws.maps.find(m=>m.id===aMap.id),aliceBefore);assert.equal(ws.discussions.filter(r=>r.kind==='relationship').length,0);
  await a.reload();await expand(a);assert.equal(await cp(a,'Alice position').count(),0);const box=async name=>a.locator('#compare-canvas .node').filter({has:a.getByText(name,{exact:true})}).boundingBox();const ab=await box('Alice position'),bb=await box('Bob response');assert(Math.abs(ab.y-bb.y)<1,'Explicit counterparts share a display row');
  await a.screenshot({path:'build/design-review/counterpart-linked.png',fullPage:true});
  await node(a,'Alice position');assert.equal(await pop(a).getByRole('button',{name:'Request counterpart',exact:true}).count(),0,'A linked node has no request action');await action(a,'View linked counterparts (1)');assert.equal(await pop(a).getByRole('button',{name:'Request counterpart',exact:true}).count(),0,'Counterpart list also hides the request');assert.match(await pop(a).innerText(),/Bob response[\s\S]*Bob worldview[\s\S]*Status Quo/);const linkedZoom=await a.locator('#compare-canvas .comparison-zoom').innerText();await action(a,'Show connected nodes');assert.equal(await a.locator('#compare-canvas .comparison-zoom').innerText(),linkedZoom,'Linked-counterpart reveal retains the current zoom');await action(a,'Close');
  // The illustrative connection and parent connection have one visible route.
  const checkEdges=async page=>{
    const pairs=await page.locator('path[data-node-pair]').evaluateAll(paths=>paths.filter(p=>getComputedStyle(p).display!=='none'&&getComputedStyle(p).visibility!=='hidden').map(p=>p.dataset.nodePair));assert.equal(new Set(pairs).size,pairs.length,'Exactly one visible edge per displayed node pair');assert.equal(await page.locator('.comparison-link,.comparison-link-hit').count(),0,'Older and selected-pair paths do not leak through the combined layer');
    const geometry=await page.locator('#compare-canvas').evaluate(canvas=>{
      const cards=[...canvas.querySelectorAll('.node,.counterpart-placeholder')].filter(el=>!el.hidden).map(el=>el.getBoundingClientRect()),paths=[...canvas.querySelectorAll('.discussion-relationship')].filter(p=>p.getAttribute('d')),badges=[...canvas.querySelectorAll('.discussion-badge')].filter(el=>!el.hidden),failures=[];
      const samples=paths.map(path=>{const points=[],length=path.getTotalLength(),matrix=path.getScreenCTM();for(let at=0;at<=length;at+=1){const p=path.getPointAtLength(at),screen=new DOMPoint(p.x,p.y).matrixTransform(matrix);points.push(screen);for(const r of cards)if(screen.x>r.left+.5&&screen.x<r.right-.5&&screen.y>r.top+.5&&screen.y<r.bottom-.5)failures.push('Relationship enters a visible card.');}return points;});
      for(const badge of badges){const r=badge.getBoundingClientRect(),cx=r.x+r.width/2,cy=r.y+r.height/2;for(const card of cards)if(r.left<card.right-.5&&r.right>card.left+.5&&r.top<card.bottom-.5&&r.bottom>card.top+.5)failures.push('Relationship label covers a visible card.');if(!samples.some(points=>points.some(p=>Math.hypot(p.x-cx,p.y-cy)<1.5)))failures.push('Relationship label floats away from its route.');}
      const hits=[...canvas.querySelectorAll('.discussion-relationship-hit')];if(hits.length!==paths.length||hits.some((hit,i)=>hit.getAttribute('d')!==paths[i].getAttribute('d')))failures.push('Every relationship needs its matching keyboard/click target.');
      return [...new Set(failures)];
    });assert.deepEqual(geometry,[]);
  };
  // A stance belongs to the selected statement; it does not create or remove its counterpart link.
  await checkEdges(a);await node(b,'Alice position');await action(b,'Endorse');await action(b,'Record position');await pop(b).getByRole('button',{name:'Edit',exact:true}).waitFor();await saved(b);await action(b,'Close');
  await a.reload();await expand(a);await checkEdges(a);assert.equal(await a.locator('.discussion-relationship').count(),1,'Counterpart plus endorsement retain one counterpart edge');
  const endorsed=((await view(store,alice)).workspace.discussions).find(r=>r.kind==='interaction'&&r.action==='endorse');assert.equal(endorsed.authorId,bob.id);await a.getByRole('button',{name:'Conversations',exact:true}).click();await pop(a).locator(`[data-entry="${endorsed.id}"]`).click();assert.match(await pop(a).innerText(),/Endorse[\s\S]*Bob/);await action(a,'Close');
  const beforeStanceMaps=structuredClone((await view(store,alice)).workspace.maps);
  for(const stance of ['Disagree','No position']){await node(a,'Bob response');await action(a,stance);await action(a,'Record position');await pop(a).getByRole('button',{name:'Edit',exact:true}).waitFor();await saved(a);await action(a,'Close');await checkEdges(a);assert.equal(await a.locator('.discussion-relationship').count(),1);assert.equal(await cp(a,'Alice position').count(),0,'A new stance does not remove the counterpart');}
  ws=(await view(store,alice)).workspace;assert.deepEqual(ws.maps,beforeStanceMaps,'Minimal stances do not adopt, revise or delete either map');assert.deepEqual(ws.discussions.filter(r=>r.kind==='interaction').map(r=>r.action).sort(),['decline','disagree','endorse']);assert.equal(ws.discussions.filter(r=>r.kind==='relationship').length,0,'Compare stances do not recreate retired paired judgments');assert.equal(ws.discussions.filter(r=>r.kind==='correspondence').length,1);await a.getByRole('button',{name:'Fit both maps',exact:true}).click();await a.screenshot({path:'build/design-review/single-edge-comparison.png',fullPage:true});

  await node(a,'Alice extra');await action(a,'Request counterpart');await action(a,'Send request');await saved(a);await action(a,'Close');
  await b.reload();await expand(b);await cp(b,'Alice extra').getByRole('button',{name:'Respond',exact:true}).click();await action(b,'No position yet');await b.locator('#discussion-body').fill('I have not formed a position on this yet.');await action(b,'No position yet');await saved(b);await action(b,'Close');
  await a.reload();await expand(a);assert.equal(await cp(a,'Alice extra').count(),1);assert.match(await cp(a,'Alice extra').innerText(),/No position yet/);await cp(a,'Alice extra').getByRole('button',{name:'View request',exact:true}).click();await action(a,'Reopen request');await a.locator('#discussion-body').fill('You mentioned an existing node that might fit.');await action(a,'Reopen request');await saved(a);await action(a,'Close');
  await b.reload();await expand(b);await node(b,'Bob position');await action(b,'Link counterpart');assert.equal(await b.locator('#counterpart-node').inputValue(),'');assert(await pop(b).getByRole('button',{name:'Link counterpart',exact:true}).isDisabled());await b.locator('#counterpart-search').fill('Alice extra');const existing=aMap.nodes.find(n=>n.title==='Alice extra');await b.locator('#counterpart-node').selectOption(existing.id);await action(b,'Link counterpart');await saved(b);await action(b,'Close');
  ws=(await view(store,alice)).workspace;assert.equal(ws.discussions.filter(r=>r.kind==='correspondence').length,2);assert.equal(ws.maps.find(m=>m.id===bMap.id).nodes.filter(n=>n.parent!==null).length,2,'Choosing a node does not create a duplicate');
  await b.setViewportSize({width:390,height:844});await b.getByRole('button',{name:'Fit both maps',exact:true}).click();await node(b,'Alice extra');await action(b,'Create counterpart in my map');await b.locator('#counterpart-title').fill('Mobile draft');assert(await b.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const rect=await pop(b).boundingBox();assert(rect.x>=0&&rect.x+rect.width<=390);await b.screenshot({path:'build/design-review/counterpart-mobile.png',fullPage:true});const mobileSubmit=pop(b).getByRole('button',{name:'Create and link counterpart',exact:true});await mobileSubmit.focus();assert(await mobileSubmit.evaluate(el=>el===document.activeElement&&el.getBoundingClientRect().bottom<=el.closest('.discussion-popover').getBoundingClientRect().bottom),'Keyboard focus scrolls the submit action into the narrow form');await b.keyboard.press('Tab');assert(await pop(b).getByRole('button',{name:'Cancel',exact:true}).evaluate(el=>el===document.activeElement));b.once('dialog',d=>d.accept());await b.keyboard.press('Enter');
  await b.setViewportSize({width:1440,height:1000});await b.reload();await expand(b);const aliceSide=await b.locator('#compare-map-a').inputValue()===aMap.id?'a':'b';await b.locator('.comparison-view-options>summary').click();await b.locator('#compare-collapse-'+aliceSide).click();await b.locator('.comparison-view-options>summary').click();await b.getByRole('button',{name:'Fit both maps',exact:true}).click();await checkEdges(b);
  await b.screenshot({path:'build/design-review/comparison-asymmetric-collapse.png',fullPage:true});
  assert.equal(await b.locator('.discussion-relationship').count(),0,'Collapsed counterparts never draw an apparent ancestor connection');
  const collapsedBadge=()=>b.getByRole('button',{name:'2 connections inside this branch',exact:true});
  await collapsedBadge().focus();await b.keyboard.press('Enter');assert.equal(await pop(b).locator('.collapsed-connection-pair').count(),2,'The branch badge lists both actual counterpart pairs');await action(b,'Close');
  await collapsedBadge().click();await pop(b).getByRole('button',{name:'Show connected nodes',exact:true}).first().click();await action(b,'Close');
  const relationshipHit=b.locator('.discussion-relationship-hit').first();await relationshipHit.focus();await b.keyboard.press('Enter');assert(await pop(b).isVisible(),'A routed relationship is still keyboard accessible');await action(b,'Close');
  const mousePoint=await relationshipHit.evaluate(path=>{const matrix=path.getScreenCTM();for(let i=1;i<100;i++){const p=path.getPointAtLength(path.getTotalLength()*i/100),screen=new DOMPoint(p.x,p.y).matrixTransform(matrix);if(document.elementFromPoint(screen.x,screen.y)===path)return {x:screen.x,y:screen.y};}return null;});assert(mousePoint,'A relationship has a clickable segment outside its cards and label');await b.mouse.click(mousePoint.x,mousePoint.y);assert(await pop(b).isVisible());await action(b,'Close');
  await b.locator('.comparison-view-options>summary').click();await b.locator('#compare-collapse-'+aliceSide).click();await b.locator('.comparison-view-options>summary').click();
  await b.setViewportSize({width:390,height:844});await b.getByRole('button',{name:'Fit both maps',exact:true}).click();await checkEdges(b);await collapsedBadge().click();const listRect=await pop(b).boundingBox();assert(listRect.x>=0&&listRect.x+listRect.width<=390,'Collapsed pair details fit a narrow viewport');assert(await b.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await b.screenshot({path:'build/design-review/comparison-asymmetric-collapse-mobile.png',fullPage:true});await action(b,'Close');
  await b.setViewportSize({width:1440,height:1000});await b.locator('.comparison-view-options>summary').click();for(const side of ['a','b'])await b.locator('#compare-collapse-'+side).click();await b.locator('.comparison-view-options>summary').click();await b.getByRole('button',{name:'Fit both maps',exact:true}).click();await checkEdges(b);assert.equal(await b.locator('.discussion-relationship').count(),0,'No frame-to-frame relationship is invented when both endpoints are hidden');assert.equal(await collapsedBadge().count(),2,'Each branch provides access to the same two underlying pairs');
  // The screenshot-shaped fixture: identical five-child trees keep all source
  // coordinates and the camera when either Low union density is selected.
  const fixtures={},fiveTitles=['Low union density','Socialists','Worker participation','Public ownership','Collective bargaining'];
  for(const actor of [alice,bob])await edit(store,actor,w=>{const m=createOwnedMap(w,{name:actor.name+' five-child map',ownerId:actor.id});m.visibility='shared';for(const [index,title]of fiveTitles.entries())m.nodes.push({id:`clarity-${actor.name}-${index}`,parent:'status',title,summary:index===0?'Union density is at historic lows.':'An independently authored position.',details:'',confidence:null,kind:'position',structuralType:'nesting',timeScope:'present',sourceTitle:'',sourceUrl:''});synchronizeIdeas(w,m);fixtures[actor.name]=m;});
  const {comparisonThread:clarity}=await startAccountComparison(store,alice.id,{aMapId:fixtures.Alice.id,bMapId:fixtures.Bob.id}),clarityURL=origin+'/?clarity#comparison='+clarity.id;
  await a.goto(clarityURL);await expand(a);
  const fixtureNode=(p,owner,title)=>p.getByRole('button',{name:`Select ${title} from ${owner} five-child map by ${owner}`,exact:true});
  const fixtureSelect=async(p,owner,title)=>{const main=fixtureNode(p,owner,title);await main.focus();await p.keyboard.press('Enter');};
  const stableGeometry=p=>p.locator('#compare-canvas .comparison-world').evaluate(world=>({camera:world.style.transform,nodes:[...world.querySelectorAll('.node')].map(card=>[card.dataset.side,card.querySelector('.node-title').textContent,card.style.transform]).sort(),folds:[...world.querySelectorAll('.toggle')].map(button=>[button.getAttribute('aria-label'),button.getAttribute('aria-expanded')]).sort()}));
  const geometryBefore=await stableGeometry(a),untouched=JSON.stringify((await view(store,alice)).workspace.maps);
  for(const owner of ['Alice','Bob','Alice','Bob']){await fixtureSelect(a,owner,'Low union density');assert.deepEqual(await stableGeometry(a),geometryBefore,'Ordinary selection does not displace siblings or fit a selected pair');assert.equal(await a.locator('.counterpart-placeholder').count(),10);await action(a,'Close');}
  assert.equal(await a.locator('#compare-canvas .node:not(.root)').count(),10);assert.equal((await view(store,alice)).workspace.discussions.filter(r=>r.comparisonId===clarity.id).length,0);
  await fixtureSelect(a,'Alice','Low union density');await a.screenshot({path:'build/design-review/comparison-five-child-selected-desktop.png',fullPage:true});await action(a,'Close');await a.setViewportSize({width:390,height:844});await a.getByRole('button',{name:'Fit both maps',exact:true}).click();const mobileGeometry=await stableGeometry(a);await fixtureSelect(a,'Bob','Low union density');assert.deepEqual(await stableGeometry(a),mobileGeometry);await a.screenshot({path:'build/design-review/comparison-five-child-selected-mobile.png',fullPage:true});await action(a,'Close');await a.setViewportSize({width:1440,height:1000});await a.getByRole('button',{name:'Fit both maps',exact:true}).click();await fixtureSelect(a,'Alice','Low union density');
  await action(a,'Link counterpart');assert.equal(await a.locator('#counterpart-node').inputValue(),'');assert(await pop(a).getByRole('button',{name:'Link counterpart',exact:true}).isDisabled());assert.equal(await a.locator('#counterpart-node option[value="status"]').count(),0);
  await a.locator('#counterpart-search').fill('Collective');assert.equal(await a.locator('#counterpart-node option').count(),2);await a.locator('#counterpart-node').selectOption('clarity-Bob-4');
  a.once('dialog',d=>d.dismiss());await action(a,'Cancel');assert.equal(await a.locator('#counterpart-node').inputValue(),'clarity-Bob-4','Declined cancel preserves the explicit counterpart choice');
  a.once('dialog',d=>d.accept());await action(a,'Cancel');assert.deepEqual(await stableGeometry(a),geometryBefore,'Cancelled chooser preserves geometry and camera');assert.equal(JSON.stringify((await view(store,alice)).workspace.maps),untouched);
  // Either owner can begin from their own node; saved maps stay byte-for-byte
  // identical, and swapping which endpoint starts the chooser cannot duplicate.
  await fixtureSelect(a,'Alice','Low union density');await action(a,'Link counterpart');await a.locator('#counterpart-search').fill('Low union');await a.locator('#counterpart-node').selectOption('clarity-Bob-0');await action(a,'Link counterpart');await saved(a);await action(a,'Close');
  assert.equal(JSON.stringify((await view(store,alice)).workspace.maps),untouched);await a.reload();await expand(a);
  await fixtureSelect(a,'Bob','Low union density');await action(a,'Link another counterpart');await a.locator('#counterpart-node').selectOption('clarity-Alice-0');await action(a,'Link counterpart');await saved(a);await action(a,'Close');
  assert.equal((await view(store,alice)).workspace.discussions.filter(r=>r.comparisonId===clarity.id&&r.kind==='correspondence').length,1,'Reversed exact pair opens its saved link');
  await b.goto(clarityURL);await expand(b);await fixtureSelect(b,'Bob','Socialists');await action(b,'Link counterpart');await b.locator('#counterpart-node').selectOption('clarity-Alice-0');await action(b,'Link counterpart');await saved(b);await action(b,'Close');
  assert.equal(JSON.stringify((await view(store,alice)).workspace.maps),untouched);await a.reload();await expand(a);await fixtureSelect(a,'Alice','Low union density');await action(a,'View linked counterparts (2)');assert.equal(await pop(a).locator('.counterpart-linked-pair').count(),2);await action(a,'Close');
  // Earlier pair judgments count as meanings of an existing pair, not another
  // counterpart. They retain their own attributed history in the grouped list.
  await edit(store,alice,w=>w.discussions.push(makeDiscussion(w,{kind:'relationship',action:'agreement',comparisonId:clarity.id,target:{type:'node',mapId:fixtures.Alice.id,nodeId:'clarity-Alice-0'},other:{type:'node',mapId:fixtures.Bob.id,nodeId:'clarity-Bob-0'}},alice.id)));
  await a.reload();await expand(a);await fixtureSelect(a,'Alice','Low union density');await action(a,'View linked counterparts (2)');assert.equal(await pop(a).locator('.counterpart-linked-pair').count(),2);await pop(a).locator('[data-counterpart-node="clarity-Bob-0"] summary').click();assert(await pop(a).getByRole('button',{name:'Earlier Agreement · Alice',exact:true}).isVisible());await action(a,'Close');
  // Review current sources before committing; rejected stale choices remain
  // open for recovery rather than mutating a foreign map or losing the draft.
  await fixtureSelect(a,'Alice','Worker participation');await action(a,'Link counterpart');await a.locator('#counterpart-node').selectOption('clarity-Bob-2');
  await edit(store,bob,w=>{const m=w.maps.find(m=>m.id===fixtures.Bob.id);m.nodes.find(n=>n.id==='clarity-Bob-2').summary='Changed while the counterpart chooser was open.';synchronizeIdeas(w,m);});
  await action(a,'Link counterpart');await pop(a).getByRole('alert').filter({hasText:'A source changed'}).waitFor();assert.equal(await a.locator('#counterpart-node').inputValue(),'clarity-Bob-2');a.once('dialog',d=>d.accept());await action(a,'Cancel');
  await a.reload();await expand(a);await fixtureSelect(a,'Alice','Worker participation');await action(a,'Link counterpart');await a.locator('#counterpart-node').selectOption('clarity-Bob-4');assert.match(await a.locator('#counterpart-preview').innerText(),/Status Quo/);
  await edit(store,bob,w=>{const m=w.maps.find(m=>m.id===fixtures.Bob.id);m.nodes.find(n=>n.id==='clarity-Bob-4').parent='goal';synchronizeIdeas(w,m);});
  await action(a,'Link counterpart');await pop(a).getByRole('alert').filter({hasText:'A source changed'}).waitFor();assert.equal(await a.locator('#counterpart-node').inputValue(),'clarity-Bob-4','A changed frame or parent path keeps the rejected choice for recovery');assert.equal((await view(store,alice)).workspace.discussions.filter(r=>r.comparisonId===clarity.id&&r.kind==='correspondence').length,2);a.once('dialog',d=>d.accept());await action(a,'Cancel');
  // A lost acknowledgment after atomic creation can be retried exactly once:
  // reuse the same staged record/node, preserving the form on the first failure.
  await fixtureSelect(a,'Bob','Public ownership');await action(a,'Create counterpart in my map');await a.locator('#counterpart-node').selectOption('goal');await a.locator('#counterpart-title').fill('A cross-frame counterpart');loseNextAcknowledgment=true;
  await action(a,'Create and link counterpart');await pop(a).getByRole('alert').filter({hasText:'acknowledgment was lost'}).waitFor();assert.equal(await a.locator('#counterpart-title').inputValue(),'A cross-frame counterpart');assert.match(await a.locator('#counterpart-preview').innerText(),/Different frame/);
  await action(a,'Create and link counterpart');await saved(a);await action(a,'Close');const afterRetry=(await view(store,alice)).workspace;assert.equal(afterRetry.maps.find(m=>m.id===fixtures.Alice.id).nodes.filter(n=>n.title==='A cross-frame counterpart').length,1);assert.equal(afterRetry.discussions.filter(r=>r.comparisonId===clarity.id&&r.kind==='correspondence').length,3,'Lost acknowledgment does not duplicate the counterpart link');
  await a.setViewportSize({width:390,height:844});await a.getByRole('button',{name:'Fit both maps',exact:true}).click();await fixtureSelect(a,'Alice','Socialists');await action(a,'Link counterpart');await a.locator('#counterpart-search').fill('Social');const chooserBounds=await pop(a).boundingBox();assert(chooserBounds.x>=0&&chooserBounds.x+chooserBounds.width<=390);await a.screenshot({path:'build/design-review/counterpart-search-mobile.png',fullPage:true});a.once('dialog',d=>d.accept());await action(a,'Cancel');
  // Empty opposite maps explain the missing candidates and offer only actions
  // whose ownership rules can actually be satisfied.
  let emptyMap;await edit(store,bob,w=>{emptyMap=createOwnedMap(w,{name:'Bob empty map',ownerId:bob.id});emptyMap.visibility='shared';});const {comparisonThread:emptyThread}=await startAccountComparison(store,alice.id,{aMapId:fixtures.Alice.id,bMapId:emptyMap.id});
  await a.setViewportSize({width:1440,height:1000});await a.goto(origin+'/?empty#comparison='+emptyThread.id);await expand(a);await fixtureSelect(a,'Alice','Socialists');await action(a,'Link counterpart');assert.match(await pop(a).innerText(),/Bob empty map has no ordinary nodes/);assert(await pop(a).getByRole('button',{name:'Link counterpart',exact:true}).isDisabled());assert.equal(await pop(a).getByRole('button',{name:'Create counterpart in my map',exact:true}).count(),0);assert(await pop(a).getByRole('button',{name:'Request counterpart',exact:true}).isVisible());await action(a,'Cancel');
  await b.goto(origin+'/?empty#comparison='+emptyThread.id);await expand(b);await fixtureSelect(b,'Alice','Socialists');await action(b,'Link counterpart');assert(await pop(b).getByRole('button',{name:'Create counterpart in my map',exact:true}).isVisible(),'Only the owner of an empty destination gets creation');assert.equal(await pop(b).getByRole('button',{name:'Request counterpart',exact:true}).count(),0);await action(b,'Cancel');
  // A node linked outside its visible frame remains truthfully linked. Filter
  // and collapse affect visibility, never the identity or count of that pair.
  await a.goto(clarityURL);await expand(a);const ghost=(page,owner,index)=>page.locator(`.counterpart-placeholder[data-source-map="${fixtures[owner].id}"][data-source-node="clarity-${owner}-${index}"]`);
  assert.match(await ghost(a,'Bob',3).innerText(),/Counterpart in another frame/);await ghost(a,'Bob',3).getByRole('button',{name:'View linked counterparts',exact:true}).click();assert.match(await pop(a).innerText(),/A cross-frame counterpart[\s\S]*In another frame/);await action(a,'Close');
  const ownSide=await a.locator('#compare-map-a').inputValue()===fixtures.Alice.id?'a':'b';await a.locator('.comparison-view-options>summary').click();await a.locator('#compare-frame-'+ownSide).selectOption('status');await a.locator('.comparison-view-options>summary').click();assert.match(await ghost(a,'Bob',3).innerText(),/Counterpart in hidden frame/);
  await a.locator('.comparison-view-options>summary').click();await a.locator('#compare-frame-'+ownSide).selectOption('all');await a.locator('#compare-collapse-'+ownSide).click();await a.locator('.comparison-view-options>summary').click();assert.match(await ghost(a,'Bob',3).innerText(),/Counterpart in collapsed branch/);await expand(a);
  const restoredLayout=async page=>page.locator('#compare-canvas .comparison-world').evaluate(world=>[...world.querySelectorAll('.node,.counterpart-placeholder')].map(el=>[el.dataset.side||el.dataset.sourceMap,el.querySelector('.node-title')?.textContent||el.dataset.sourceNode,el.style.transform]).sort());
  const beforePairLayout=await restoredLayout(a),beforePairMaps=JSON.stringify((await view(store,alice)).workspace.maps);
  for(let iteration=0;iteration<2;iteration++){
    await ghost(a,'Alice',2).getByRole('button',{name:'Link counterpart',exact:true}).click();await a.locator('#counterpart-node').selectOption('clarity-Bob-2');await action(a,'Link counterpart');await saved(a);assert.equal(await ghost(a,'Alice',2).count(),0,'A saved adjacent pair replaces both ghosts');assert.equal(await ghost(a,'Bob',2).count(),0);
    if(!iteration){await b.goto(clarityURL);await expand(b);await fixtureSelect(b,'Alice','Worker participation');await action(b,'View linked counterparts (1)');await pop(b).locator('.counterpart-linked-pair summary').click();await action(b,'Counterpart link · Alice');assert.equal(await pop(b).getByRole('button',{name:'Withdraw',exact:true}).count(),0,'The other participant cannot withdraw the authored link');await action(b,'Close');}
    if(iteration){await action(a,'Close');await fixtureSelect(a,'Bob','Worker participation');await action(a,'View linked counterparts (1)');await pop(a).locator('.counterpart-linked-pair summary').click();await action(a,'Counterpart link · Alice');}
    const withdrawOwner=iteration?'Bob':'Alice',beforeWithdraw=await fixtureNode(a,withdrawOwner,'Worker participation').boundingBox(),withdrawZoom=await a.locator('#compare-canvas .comparison-zoom').innerText();a.once('dialog',d=>d.accept());await action(a,'Withdraw');await saved(a);const afterWithdraw=await fixtureNode(a,withdrawOwner,'Worker participation').boundingBox();assert(Math.abs(afterWithdraw.x-beforeWithdraw.x)<1&&Math.abs(afterWithdraw.y-beforeWithdraw.y)<1,'Withdrawal anchors the initiating node');assert.equal(await a.locator('#compare-canvas .comparison-zoom').innerText(),withdrawZoom);assert.match(await ghost(a,'Alice',2).innerText(),/No counterpart linked/);assert.deepEqual(await restoredLayout(a),beforePairLayout,'Repeated pair and withdrawal restore occupied geometry without accumulating empty slots');
  }
  assert.equal(JSON.stringify((await view(store,alice)).workspace.maps),beforePairMaps,'Pairing and withdrawing do not rewrite either source map');await a.reload();await expand(a);assert.deepEqual(await restoredLayout(a),beforePairLayout,'Unpaired geometry survives cold reload');
  // Permitted link history survives a deleted source endpoint, without showing
  // the deleted wording as a current card or a newly unlinked suggestion.
  await ghost(a,'Alice',2).getByRole('button',{name:'Link counterpart',exact:true}).click();await a.locator('#counterpart-node').selectOption('clarity-Bob-2');await action(a,'Link counterpart');await saved(a);await action(a,'Close');
  await edit(store,bob,w=>{const m=w.maps.find(m=>m.id===fixtures.Bob.id);m.nodes=m.nodes.filter(n=>n.id!=='clarity-Bob-2');synchronizeIdeas(w,m);});await a.reload();await expand(a);assert.match(await ghost(a,'Alice',2).innerText(),/Counterpart unavailable/);assert.equal(await ghost(a,'Alice',2).getByRole('button',{name:'Link counterpart',exact:true}).count(),0);await ghost(a,'Alice',2).getByRole('button',{name:'View saved details',exact:true}).click();assert.equal(await pop(a).locator('.counterpart-linked-pair h3').innerText(),'Counterpart unavailable');assert.equal(await pop(a).getByRole('button',{name:'Show connected nodes',exact:true}).count(),0,'An unavailable endpoint cannot be revealed as a current node');await action(a,'Close');
  assert.deepEqual(errors,[]);console.log('Counterpart browser checks passed: stable five-child selection, direct searchable two-way linking, explicit choice and cancellation, grouped meanings, unchanged maps, duplicate protection, source-change validation, atomic retry, requests, create permissions, independent stances, geometry, reload and narrow screens.');
}catch(error){for(const [i,context]of browser.contexts().entries())for(const page of context.pages()){await page.screenshot({path:`build/design-review/counterpart-failure-${i}.png`,fullPage:true});console.error((await page.locator('body').innerText()).slice(-3500));}console.error(errors);throw error;}finally{await browser.close();await new Promise(r=>server.close(r));}
