import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {alice,bob,memoryStore,seedActor,edit,view,addNode} from './accounts.test.mjs';
import {startAccountComparison} from '../worker/account-api.mjs';
import {makeDiscussion,discussionHealth} from '../dist/discussion.mjs';
import {synchronizeIdeas} from '../dist/adoption.mjs';
import {stableJSON} from '../dist/account-model.mjs';
import {validateWorkspace} from '../dist/workspace.mjs';
import {validateAccountChanges} from '../worker/account-policy.mjs';

export async function exerciseDiscussions(store){
  for(const actor of [alice,bob])await edit(store,actor,w=>{const map=w.maps.find(m=>m.ownerId===actor.id);map.visibility='shared';addNode(w,actor,actor.name+' conversation position');});
  let ws=(await view(store,alice)).workspace;
  const a=ws.maps.find(m=>m.ownerId===alice.id),b=ws.maps.find(m=>m.ownerId===bob.id);
  const at={type:'node',mapId:a.id,nodeId:a.nodes.at(-1).id},bt={type:'node',mapId:b.id,nodeId:b.nodes.at(-1).id};
  const {comparisonThread:thread}=await startAccountComparison(store,alice.id,{aMapId:a.id,bMapId:b.id});
  const save=async(actor,input,oldId=null)=>{let result;await edit(store,actor,w=>{const old=w.discussions.find(r=>r.id===oldId);result=makeDiscussion(w,{comparisonId:thread.id,...input},actor.id,old);w.discussions=w.discussions.filter(r=>r.id!==result.id);w.discussions.push(result);});return result;};
  const request=await save(alice,{kind:'counterpart',action:'counterpart',target:at});
  const relation=await save(alice,{kind:'relationship',action:'disagreement',target:at,other:bt});
  assert((await view(store,bob)).workspace.discussions.some(r=>r.id===relation.id),'One author is enough to display the shared relationship');
  assert.equal(relation.question,undefined);assert.equal(relation.judgments,undefined);
  await assert.rejects(()=>save(alice,{kind:'counterpart',action:'counterpart',target:at}),/already linked/);
  const adoption=await save(alice,{kind:'adoption',action:'adoption',target:at,body:'Please consider adding this position to your map.'});
  assert((await view(store,bob)).workspace.discussions.some(r=>r.id===adoption.id),'Adoption suggestions are shared with the other map author');
  for(const action of ['explain','example','evidence','question'])await save(alice,{kind:'inquiry',action,target:bt,body:'Please explain your position.'});
  const edge={type:'edge',mapId:b.id,edgeId:`structure:${bt.nodeId}`};
  const argument=await save(alice,{kind:'argument',action:'fallacy',target:edge,body:'This inference appears circular because its premise repeats its conclusion.'});
  await save(bob,{kind:'reply',action:'reply',target:{type:'entry',entryId:argument.id},layer:'arguments',body:'Here is why I think the premise is independent.'});
  const context=await save(bob,{kind:'context',action:'context',target:edge,body:'Evidence: independently reproducible observation. Standard: reproducibility.'});
  assert.equal(context.comparisonId,null,'Source context is reusable across comparisons');
  await save(alice,{...relation,body:'The conclusions conflict.'},relation.id);
  ws=(await view(store,alice)).workspace;assert.equal(ws.discussions.find(r=>r.id===relation.id).history.length,1);
  assert.deepEqual(validateWorkspace(JSON.parse(JSON.stringify(ws))),ws,'Conversations survive portable round trip');
  const template=ws.discussions.find(r=>r.kind==='inquiry');
  const first={...template,sourceSnapshots:undefined,id:'cycle-first',target:{type:'entry',entryId:'cycle-second'}};
  const second={...template,sourceSnapshots:undefined,id:'cycle-second',target:{type:'entry',entryId:'cycle-first'}};
  assert.throws(()=>validateWorkspace({...ws,discussions:[...ws.discussions,first,second]}),/cycle/,'Imported conversations cannot refer back to themselves');
  assert.throws(()=>validateWorkspace({...ws,discussions:[...ws.discussions,first]}),/same comparison/,'Missing entry references fail before loading the canvas');
  assert.throws(()=>validateWorkspace({...ws,discussions:[...ws.discussions,{...template,id:'extra-source',other:at}]}),/second source/);
  const snapshot=await store.snapshot(),record=snapshot.records.find(r=>r.id===relation.id&&r.kind==='discussion');
  assert.throws(()=>validateAccountChanges(snapshot,bob.id,[{kind:'discussion',id:relation.id,expectedRevision:record.revision,value:{...record.value,body:'Forged'}}]),e=>e.status===403);
  await assert.rejects(()=>save(alice,{kind:'context',action:'context',target:edge,body:'Forged standards'}),/Only the map author/);
  await assert.rejects(()=>save(bob,{kind:'counterpart',action:'counterpart',target:at}),/own node/);
  await assert.rejects(()=>save(bob,{kind:'adoption',action:'adoption',target:at}),/own node/);
  await assert.rejects(()=>save(alice,{kind:'inquiry',action:'question',target:at,body:'Own inquiry'}),/other person/);
  await assert.rejects(()=>save(alice,{kind:'relationship',action:'agreement',target:bt,other:at}),/already recorded/);
  await assert.rejects(()=>save(alice,{kind:'argument',action:'challenge',target:{...edge,edgeId:'missing'},body:'Missing target'}),/source changed/);
  const evidence=await save(alice,{kind:'argument',action:'evidence',target:{type:'entry',entryId:argument.id},body:'A supporting reference.',referenceUrl:'https://example.org/evidence'});
  assert.equal(evidence.referenceUrl,'https://example.org/evidence');
  await assert.rejects(()=>save(alice,{kind:'argument',action:'evidence',target:bt,body:'Unsafe link',referenceUrl:'javascript:alert(1)'}),/http or https/);
  const original=stableJSON(relation.sourceSnapshots);
  await edit(store,bob,w=>{const map=w.maps.find(m=>m.id===b.id);map.nodes.find(n=>n.id===bt.nodeId).details='Revised source explanation';synchronizeIdeas(w,map);});
  ws=(await view(store,alice)).workspace;let current=ws.discussions.find(r=>r.id===relation.id);
  assert.equal(discussionHealth(ws,current).state,'changed');assert.equal(stableJSON(current.sourceSnapshots),original);
  current=await save(alice,{...current,reviewSources:true},current.id);
  ws=(await view(store,alice)).workspace;assert.equal(discussionHealth(ws,current).state,'current');assert.equal(stableJSON(current.sourceSnapshots),original,'Review never replaces the original wording');
  const forged=structuredClone(current);forged.sourceSnapshots[0].label='Forged earlier wording';
  const forgedEdit=makeDiscussion(ws,{...forged,body:'New text'},alice.id,forged),latestSnapshot=await store.snapshot(),latestRecord=latestSnapshot.records.find(r=>r.kind==='discussion'&&r.id===current.id);
  assert.throws(()=>validateAccountChanges(latestSnapshot,alice.id,[{kind:'discussion',id:current.id,expectedRevision:latestRecord.revision,value:forgedEdit}]),/history|wording|source/i);
  const legacy=structuredClone(current);delete legacy.sourceSnapshots;delete legacy.reviewedSources;
  assert.equal(discussionHealth(ws,legacy).state,'unrecorded','Earlier records must not pretend to have captured original wording');
  const deleted=structuredClone(ws);deleted.maps.find(m=>m.id===b.id).nodes=deleted.maps.find(m=>m.id===b.id).nodes.filter(n=>n.id!==bt.nodeId);
  validateWorkspace(deleted);assert.equal(discussionHealth(deleted,current).state,'unavailable');assert.equal(stableJSON(current.sourceSnapshots),original,'Deleting a source leaves its discussed wording available');
  await edit(store,bob,w=>{w.maps.find(m=>m.id===b.id).visibility='private';});
  assert(!(await view(store,alice)).workspace.discussions.some(r=>[relation.id,context.id,request.id,adoption.id].includes(r.id)),'Hidden source removes shared conversation and definitions');
  await assert.rejects(()=>save(alice,{kind:'argument',action:'challenge',target:at,body:'Unavailable comparison'}),/Both comparison maps|Invalid conversation membership/);
  await edit(store,bob,w=>{w.maps.find(m=>m.id===b.id).visibility='shared';});
  console.log('On-map conversation persistence, authorship, replies, edge targets, source context, privacy and history passed.');
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const store=memoryStore();for(const actor of [alice,bob])await seedActor(store,actor);await exerciseDiscussions(store);}
