import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {fixture,alice,bob,organizer} from './facilitation-fixture.mjs';
import {handleAccountAPI} from '../worker/account-api.mjs';
const f=await fixture(),errors=[];
const server=createServer(async(req,res)=>{try{let body='';for await(const chunk of req)body+=chunk;const url=new URL(req.url,f.env.APP_ORIGIN);if(url.pathname.startsWith('/api/')){const actor=req.headers['x-test-actor']==='alice'?alice:req.headers['x-test-actor']==='bob'?bob:organizer;const response=await handleAccountAPI(new Request(url,{method:req.method,headers:req.headers,...(body?{body}:{})}),f.env,{store:f.store,auth:f.auth(actor)});res.writeHead(response.status,Object.fromEntries(response.headers));return res.end(await response.text());}const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!/^[a-z0-9.-]+$/.test(name)){res.writeHead(404);return res.end();}let content=await readFile('dist/'+name,'utf8');if(name==='index.html')content=content.replace('src="./app.mjs"','src="./beta-boot.mjs"').replace('</head>','<link rel="stylesheet" href="./accounts.css"></head>');res.setHeader('content-type',name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript');res.end(content);}catch(e){res.writeHead(500);res.end(e.message);}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));f.env.APP_ORIGIN='http://127.0.0.1:'+server.address().port;
const {chromium}=await import(pathToFileURL(process.env.HARMONIOUS_PLAYWRIGHT)),browser=await chromium.launch({headless:true,channel:process.env.HARMONIOUS_BROWSER||'msedge'});
try{
 await mkdir('build/design-review',{recursive:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),a=await context.newPage(),other=await context.newPage(),participant=await browser.newPage({extraHTTPHeaders:{'x-test-actor':'alice'}});for(const p of [a,other,participant]){p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));await p.goto(f.env.APP_ORIGIN);await p.locator('body:not(.account-locked)').waitFor();}
 const menu=async(p,label)=>{await p.locator('.account-menu > summary').click();await p.getByRole('button',{name:label,exact:true}).click();};
 await menu(a,'Test accounts');const list=a.locator('.test-account-row').filter({hasText:'Alice'});await list.getByRole('button',{name:'Facilitation',exact:true}).click();let dialog=a.getByRole('dialog',{name:'Facilitation for Alice'});await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Enable facilitation',exact:true}).click();await dialog.getByRole('button',{name:'Facilitate for Alice',exact:true}).click();
 await a.locator('#facilitator-banner').waitFor({state:'visible'});assert.match(await a.locator('#facilitator-banner').innerText(),/Facilitating for Alice.*Signed in as Taylor/s);assert.equal(await other.locator('#facilitator-banner').isVisible(),false);
 // Close the account administration dialog left beneath the permission review.
 if(await a.locator('.test-accounts-dialog').isVisible())await a.locator('.test-accounts-dialog').getByRole('button',{name:'Close',exact:true}).click();
 await a.getByRole('button',{name:'Open map',exact:true}).first().click();await a.locator('#world .node').first().getByRole('button',{name:/Status Quo|Select/}).first().click();
 await a.getByRole('button',{name:'Edit frame details',exact:true}).click();await a.locator('#summary').fill('A facilitator’s draft, not yet Alice’s position.');await a.locator('.node-face-done').click();
 await a.locator('#facilitator-banner').getByRole('button',{name:'Review contribution'}).click();dialog=a.getByRole('dialog',{name:'Contribution for Alice'});await dialog.getByRole('button',{name:'Save draft for Alice to review',exact:true}).click();await dialog.waitFor({state:'hidden'});
 assert(!(await f.store.snapshot()).records.some(r=>JSON.stringify(r.value).includes('A facilitator’s draft')));
 await menu(participant,'Facilitation & drafts');let pd=participant.getByRole('dialog',{name:'Facilitation & drafts'});await pd.getByText(/Draft for Alice · pending/).click();await pd.getByRole('button',{name:'Approve this draft'}).click();await pd.getByText(/Draft for Alice · approved/).waitFor();await pd.getByRole('button',{name:'Close',exact:true}).click();
 await menu(a,'Refresh maps');await a.locator('.facilitator-badge').first().waitFor();assert.match(await a.locator('.facilitator-badge').first().innerText(),/Entered by Taylor/);
 assert(await a.locator('#world .facilitator-node-badge').first().evaluate(el=>{const a=el.getBoundingClientRect(),b=el.parentElement.getBoundingClientRect();return a.top>=b.top&&a.bottom<=b.bottom;}),'Attribution must appear inside the visible node face');await a.waitForFunction(()=>parseFloat(document.getElementById('zoom').value||document.getElementById('zoom').textContent)>10);await a.screenshot({path:'build/design-review/facilitation-map.png'});
 await a.locator('#world .node[data-id="status"] .node-add-child').click();await a.locator('#child-title').fill('Entered during Alice’s assisted session');await a.locator('#child-form').getByRole('button',{name:'Add child node',exact:true}).click();
 await a.locator('#facilitator-banner').getByRole('button',{name:'Exit facilitation'}).click();assert(await a.locator('#facilitator-banner').isVisible(),'Pending contribution prevents participant switching');
 await a.locator('#facilitator-banner').getByRole('button',{name:'Review contribution'}).click();dialog=a.getByRole('dialog',{name:'Contribution for Alice'});await dialog.getByRole('checkbox').check();let lost=false;await a.route('**/api/facilitation/record',async route=>{if(!lost){lost=true;await route.fetch();return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Simulated lost facilitator acknowledgement'})});}return route.continue();});await dialog.getByRole('button',{name:'Record for Alice',exact:true}).click();await dialog.getByText('Simulated lost facilitator acknowledgement',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Record for Alice',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal((await f.store.snapshot()).records.filter(r=>r.kind==='map').flatMap(r=>r.value.nodes).filter(n=>n.title==='Entered during Alice’s assisted session').length,1);
 await a.locator('#facilitator-banner').getByRole('button',{name:'Exit facilitation'}).click();await a.locator('#facilitator-banner').waitFor({state:'hidden'});await a.locator('#account-display').getByText('Taylor',{exact:true}).waitFor();
 await menu(participant,'Facilitation & drafts');participant.once('dialog',d=>d.accept());await participant.getByRole('button',{name:'Stop facilitation',exact:true}).click();await participant.getByText('Alice · Stopped',{exact:true}).waitFor();await participant.setViewportSize({width:390,height:844});assert(await participant.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await participant.screenshot({path:'build/design-review/facilitation-narrow.png'});
 assert.deepEqual(errors,[]);console.log('Facilitation browser: explicit permission, separate tab identity, unpublished node draft, participant approval, attribution, exit, revocation and narrow review passed.');
}finally{await browser.close();await new Promise(r=>server.close(r));await f.db.close();}
