import assert from 'node:assert/strict';
import {exampleMap,exampleRelations,roots} from '../dist/data.mjs';
import {validateGraph,validateRelationship,allowedRelationTypes,canonicalRelationType,createChildStatement,frameOf,removeBranch,revealPath,graphEdges} from '../dist/model.mjs';
import {layoutForest} from '../dist/layout.mjs';
const nodes=exampleMap(),relations=exampleRelations();
validateGraph(nodes,roots,relations);
assert.equal(frameOf(nodes,'a211'),'action');
assert.equal(frameOf(nodes,'missing'),null);
assert.deepEqual(allowedRelationTypes(nodes,'s1','a1'),['reason','cause','addresses']);
assert.deepEqual(allowedRelationTypes(nodes,'a1','g1'),['reason','cause','enables']);
assert.deepEqual(allowedRelationTypes(nodes,'g3','s2'),['reason','cause']);
assert.deepEqual(allowedRelationTypes(nodes,'a1','s1'),['reason','cause']);
assert.deepEqual(allowedRelationTypes(nodes,'s1','s2'),['reason','cause']);
assert.deepEqual(allowedRelationTypes(nodes,'status','s1'),[]);assert.deepEqual(allowedRelationTypes(nodes,'s1','goal'),[]);
assert.equal(canonicalRelationType('causal'),'cause');assert.equal(canonicalRelationType('motivates'),'addresses');assert.equal(canonicalRelationType('aims_for'),'enables');
assert.throws(()=>validateRelationship(nodes,relations,{id:'alias-duplicate',from:'s1',to:'a1',type:'addresses'}),/already exists/);
assert.throws(()=>validateRelationship(nodes,relations,{id:'wrong-direction',from:'a1',to:'s1',type:'addresses'}));
assert.throws(()=>validateRelationship(nodes,relations,{id:'wrong-frame',from:'status',to:'g1',type:'enables'}));
validateRelationship(nodes,relations,{id:'cross-frame-reason',from:'g3',to:'s2',type:'reason'});
assert.throws(()=>validateRelationship(nodes,relations,{id:'new',from:'s1',to:'s1',type:'related'}));
assert.throws(()=>validateRelationship(nodes,relations,{id:'new',from:'s1',to:'a1',type:'motivates'}),/already exists/);
assert.throws(()=>validateRelationship(nodes,relations,{id:'new',from:'g3',to:'s2',type:'counterpart'}),/already exists/);
assert.throws(()=>validateRelationship(nodes,relations,{id:'new',from:'missing',to:'a1',type:'related'}));
validateRelationship(nodes,relations,{...relations[0],note:'Updated note'},relations[0].id);
assert.throws(()=>validateGraph(nodes.map(n=>n.id==='a21'?{...n,kind:'position'}:n),roots,relations),/requires a Position under a Question/);
assert.throws(()=>validateGraph(nodes.map(n=>n.id==='a211'?{...n,kind:'explainer'}:n),roots,relations),/requires a Position under a Question/);
for(const id of ['status','a211'])assert.throws(()=>validateGraph(nodes.map(n=>n.id===id?{...n,sourceUrl:'javascript:alert(1)'}:n),roots,relations),/http or https/);
validateGraph(nodes.map(n=>n.id==='a211'?{...n,sourceUrl:'https://example.org/reference'}:n),roots,relations);
const unchangedParents=nodes.map(n=>[n.id,n.parent]);
const connected=[...relations,{id:'new',from:'s11',to:'s22',type:'related',note:''}];
validateGraph(nodes,roots,connected);assert.deepEqual(nodes.map(n=>[n.id,n.parent]),unchangedParents,'Additional links preserve structural parents');
const unified=graphEdges(nodes,connected);assert.equal(unified.length,nodes.length-3+connected.length);assert(unified.find(e=>e.to==='a211'&&e.structural).type==='answer');
const oldExpanded=new Set(['goal']),expanded=revealPath(nodes,'a211',oldExpanded);assert.deepEqual([...oldExpanded],['goal']);assert(expanded.has('action')&&expanded.has('a2')&&expanded.has('a21'));assert(layoutForest(nodes,roots,expanded).positions.has('a211'));
const removed=removeBranch(nodes,relations,'s1');assert(!removed.nodes.some(n=>n.id==='s112-example'));assert(!removed.relations.some(e=>removed.removed.has(e.from)||removed.removed.has(e.to)));assert(removed.relations.some(e=>e.id==='r5'));validateGraph(removed.nodes,roots,removed.relations);
assert.throws(()=>removeBranch(nodes,relations,'status'),/frame cannot be deleted/);
const child=createChildStatement(nodes,'a21','plain-child');assert.equal(child.node.kind,'position');assert.equal(child.node.structuralType,'nesting');assert.equal(child.relation,null,'Nesting does not assert reasoning, even below a legacy Question');
const reason=createChildStatement(nodes,'a21','supporting-child',{reasonId:'supporting-edge'});assert.equal(reason.node.parent,'a21');assert.deepEqual(reason.relation,{id:'supporting-edge',from:'supporting-child',to:'a21',type:'reason',note:''});validateGraph([...nodes,reason.node],roots,[...relations,reason.relation]);
assert.throws(()=>createChildStatement(nodes,'missing','bad-child'),/parent node/);assert.throws(()=>createChildStatement(nodes,'status','bad-reason',{reasonId:'bad-reason-edge'}),/Choose a statement/);assert.throws(()=>createChildStatement(nodes,'a1','s1'),/Duplicate node/);
console.log('PASS: statement creation, explicit directed reasons, cross-frame reasoning, canonical edge types and legacy aliases, nesting independence, duplicate and self-link prevention, source URLs, and branch removal.');
