import assert from 'node:assert/strict';
import {exampleMap,exampleRelations,roots} from '../dist/data.mjs';
import {validateGraph,validateRelationship,allowedRelationTypes,frameOf,removeBranch,revealPath,graphEdges} from '../dist/model.mjs';
import {layoutForest} from '../dist/layout.mjs';
const nodes=exampleMap(),relations=exampleRelations();
validateGraph(nodes,roots,relations);
assert.equal(frameOf(nodes,'a211'),'action');
assert.equal(frameOf(nodes,'missing'),null);
assert.deepEqual(allowedRelationTypes(nodes,'s1','a1'),['motivates']);
assert.deepEqual(allowedRelationTypes(nodes,'a1','g1'),['aims_for']);
assert.deepEqual(allowedRelationTypes(nodes,'g3','s2'),['counterpart']);
assert.deepEqual(allowedRelationTypes(nodes,'a1','s1'),[]);
assert.throws(()=>validateRelationship(nodes,relations,{id:'new',from:'s1',to:'s1',type:'related'}));
assert.throws(()=>validateRelationship(nodes,relations,{id:'new',from:'s1',to:'a1',type:'motivates'}),/already exists/);
assert.throws(()=>validateRelationship(nodes,relations,{id:'new',from:'g3',to:'s2',type:'counterpart'}),/already exists/);
assert.throws(()=>validateRelationship(nodes,relations,{id:'new',from:'missing',to:'a1',type:'related'}));
validateRelationship(nodes,relations,{...relations[0],note:'Updated note'},relations[0].id);
assert.throws(()=>validateGraph(nodes.map(n=>n.id==='a21'?{...n,kind:'position'}:n),roots,relations),/requires a Position under a Question/);
assert.throws(()=>validateGraph(nodes.map(n=>n.id==='a211'?{...n,kind:'explainer'}:n),roots,relations),/requires a Position under a Question/);
for(const id of ['status','a211'])assert.throws(()=>validateGraph(nodes.map(n=>n.id===id?{...n,sourceUrl:'javascript:alert(1)'}:n),roots,relations),/http or https/);
validateGraph(nodes.map(n=>n.id==='a211'?{...n,sourceUrl:'https://example.org/reference'}:n),roots,relations);
const unchangedParents=nodes.map(n=>[n.id,n.parent]);
const connected=[...relations,{id:'new',from:'s11',to:'s22',type:'related',note:''}];
validateGraph(nodes,roots,connected);assert.deepEqual(nodes.map(n=>[n.id,n.parent]),unchangedParents,'Additional links preserve structural parents');
const unified=graphEdges(nodes,connected);assert.equal(unified.length,nodes.length-3+connected.length);assert(unified.find(e=>e.to==='a211'&&e.structural).type==='answer');
const oldExpanded=new Set(['goal']),expanded=revealPath(nodes,'a211',oldExpanded);assert.deepEqual([...oldExpanded],['goal']);assert(expanded.has('action')&&expanded.has('a2')&&expanded.has('a21'));assert(layoutForest(nodes,roots,expanded).positions.has('a211'));
const removed=removeBranch(nodes,relations,'s1');assert(!removed.nodes.some(n=>n.id==='s112-example'));assert(!removed.relations.some(e=>removed.removed.has(e.from)||removed.removed.has(e.to)));assert(removed.relations.some(e=>e.id==='r5'));validateGraph(removed.nodes,roots,removed.relations);
assert.throws(()=>removeBranch(nodes,relations,'status'),/frame cannot be deleted/);
console.log('PASS: typed questions and answers, cross-frame direction, duplicate and self-link prevention, parent independence, collapsed endpoint reveal, source URLs, and removal of connected branches.');
