import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {alice,bob,memoryStore,seedActor,edit,addNode,view} from './accounts.test.mjs';
import {accountWorkspace,saveAccountChanges,startAccountComparison} from '../worker/account-api.mjs';
import {makeDiscussion} from '../dist/discussion.mjs';
import {synchronizeIdeas} from '../dist/adoption.mjs';

// Disposable account UI: Inquiry is a view foundation and must not write data.
const playwright=process.env.HARMONIOUS_PLAYWRIGHT;if(!playwright)throw Error('Set HARMONIOUS_PLAYWRIGHT.');
const {chromium}=await import(pathToFileURL(playwright)),store=memoryStore(),ids={};
for(const actor of [alice,bob]){await seedActor(store,actor);await edit(store,actor,ws=>{const map=ws.maps.find(m=>m.ownerId===actor.id);map.visibility='shared';map.name=actor.name+' reflection map';for(const title of actor===alice?['Evening meeting','Quiet source without reasons','Nested source']:['Daytime meeting']){const n=addNode(ws,actor,title);n.kind='position';n.parent=title==='Nested source'?ids['Evening meeting']:'status';n.summary='Original source explanation for '+title;ids[title]=n.id;}synchronizeIdeas(ws,map);});}
const initial=(await view(store,alice)).workspace,aMap=initial.maps.find(m=>m.ownerId===alice.id),bMap=initial.maps.find(m=>m.ownerId===bob.id),at={type:'node',mapId:aMap.id,nodeId:ids['Evening meeting']};
const {comparisonThread:thread}=await startAccountComparison(store,alice.id,{aMapId:aMap.id,bMapId:bMap.id});
const seed=async(actor,input)=>{let result;await edit(store,actor,ws=>{result=makeDiscussion(ws,{comparisonId:thread.id,...input},actor.id);ws.discussions.push(result);});return result;};
const reason=await seed(alice,{kind:'argument',action:'reason',target:at,body:'Most respondents prefer evening.'}),child=await seed(alice,{kind:'argument',action:'reason',target:{type:'entry',entryId:reason.id},body:'Eighteen replies chose the evening slot.'}),challenge=await seed(bob,{kind:'argument',action:'challenge',target:{type:'inference',entryId:reason.id},body:'Respondents may not represent all members.'});
const writes=[],errors=[];
const json=(res,status,value)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(value));};
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),actor=req.headers['x-test-actor']==='bob'?bob:alice;if(url.pathname.startsWith('/api/')){let raw='';for await(const chunk of req)raw+=chunk;const input=raw?JSON.parse(raw):null;if(url.pathname==='/api/session'){json(res,200,{configured:true,actor,signup:{mode:'public'}});return;}if(url.pathname==='/api/comparisons'){json(res,200,await startAccountComparison(store,actor.id,input));return;}if(url.pathname==='/api/workspace'&&req.method==='PUT'){const result=await saveAccountChanges(store,actor.id,input.changes);writes.push(input.changes);json(res,200,result);return;}json(res,200,await accountWorkspace(store,actor));return;}const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!/^[a-z0-9.-]+$/.test(name)){res.writeHead(404);res.end();return;}let content=await readFile(resolve('dist',name),'utf8');if(name==='index.html')content=content.replace('src="./app.mjs"','src="./beta-boot.mjs"').replace('</head>','<link rel="stylesheet" href="./accounts.css"></head>');res.setHeader('content-type',name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'text/javascript');res.end(content);}catch(e){json(res,e.status||500,{error:e.message});}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,channel:process.env.HARMONIOUS_BROWSER||'msedge'});
try{
  await mkdir('build/design-review',{recursive:true});
  const context=await browser.newContext({viewport:{width:1440,height:1000},extraHTTPHeaders:{'x-test-actor':'alice'}}),a=await context.newPage();a.setDefaultTimeout(15000);a.on('pageerror',e=>errors.push(e.message));
  const pop=a.locator('.discussion-popover'),action=name=>pop.getByRole('button',{name,exact:true}).click(),close=async()=>{if(await pop.isVisible())await action('Close');};
  const load=async()=>{await a.goto(origin+'/#comparison='+thread.id);await a.locator('.comparison-view-options>summary').click();for(const side of ['a','b'])await a.locator('#compare-all-'+side).click();await a.locator('.comparison-view-options>summary').click();};
  const mode=name=>a.locator('#reasoning-'+name+'-mode').click();
  const node=async title=>{await close();const button=a.locator('#compare-canvas .node-main').filter({has:a.getByText(title,{exact:true})}).first();await button.focus();await a.keyboard.press('Enter');};
  const unchanged=structuredClone((await view(store,alice)).workspace);
  await load();for(const name of ['compare','inquiry','argument'])assert(await a.locator('#reasoning-'+name+'-mode').isVisible());
  await mode('inquiry');await node('Daytime meeting');assert.match(await pop.innerText(),/Bob[\s\S]*Original source explanation[\s\S]*Inquiry tools are coming next/);assert.deepEqual(await pop.getByRole('button').allTextContents(),['Close'],'Inquiry has its own unassigned interaction menu');assert.equal(await a.locator('[data-layer="inquiries"]').isVisible(),false);assert.equal(await a.locator('.reasoning-card,.reflection-marker').count(),0);
  await close();const edge=a.locator('.discussion-edge-hit:not(.discussion-relationship-hit)').first();await edge.focus();await a.keyboard.press('Enter');assert.match(await pop.innerText(),/Inquiry tools are coming next/);assert.deepEqual(await pop.getByRole('button').allTextContents(),['Close']);
  await close();const camera=await a.locator('#compare-canvas .comparison-world').getAttribute('style');await mode('compare');await mode('inquiry');assert.equal(await a.locator('#compare-canvas .comparison-world').getAttribute('style'),camera,'Mode changes preserve the canvas camera');
  await mode('compare');await node('Daytime meeting');await action('Ask');await a.locator('#discussion-action').selectOption('example');await a.locator('#discussion-body').fill('Keep this Compare draft.');await mode('inquiry');assert.equal(await pop.isVisible(),false);await mode('argument');assert.equal(await pop.isVisible(),false);await mode('compare');assert.equal(await a.locator('#discussion-body').inputValue(),'Keep this Compare draft.');assert.equal(await a.locator('#discussion-action').inputValue(),'example');a.once('dialog',d=>d.accept());await close();
  await mode('argument');await node('Evening meeting');await action('Explain my reasoning');await a.locator('#discussion-body').fill('Keep this Argument draft.');await mode('inquiry');assert.equal(await pop.isVisible(),false);assert.equal(await a.locator('.reasoning-card').count(),0);await mode('argument');assert.equal(await a.locator('#discussion-body').inputValue(),'Keep this Argument draft.');a.once('dialog',d=>d.accept());await close();
  await a.getByRole('button',{name:'Conversations',exact:true}).click();await pop.getByRole('button',{name:'Reason · Alice · Evening meeting',exact:true}).click();await mode('inquiry');assert.equal(await a.locator('#reasoning-inquiry-mode').getAttribute('aria-pressed'),'true','Inquiry does not jump back to the previous argument');assert.deepEqual(await pop.getByRole('button').allTextContents(),['Close']);
  await a.screenshot({path:'build/design-review/inquiry-desktop.png',fullPage:true});await a.setViewportSize({width:390,height:844});await a.waitForFunction(()=>{const r=document.querySelector('.discussion-popover').getBoundingClientRect();return document.documentElement.scrollWidth<=innerWidth&&r.left>=0&&r.right<=innerWidth+1;});for(const name of ['compare','inquiry','argument'])assert(await a.locator('#reasoning-'+name+'-mode').isVisible());await a.screenshot({path:'build/design-review/inquiry-mobile.png',fullPage:true});await a.setViewportSize({width:1440,height:1000});
  await close();await a.getByRole('button',{name:'Conversations',exact:true}).click();assert.match(await pop.innerText(),/Inquiry tools are coming next/);assert.equal(await pop.locator('.discussion-list-item').count(),0,'No existing interactions are silently reassigned');await close();
  await a.locator('#individual-mode').click();await a.locator('#library-workspace').waitFor();await a.getByRole('button',{name:'Open map',exact:true}).first().click();await a.locator('#editor-main').waitFor();
  const after=(await view(store,alice)).workspace;assert.deepEqual(after.maps,unchanged.maps);assert.deepEqual(after.discussions,unchanged.discussions);assert.equal(writes.length,0,'Adding/selecting Inquiry does not change saved records');
  await a.goto(origin);await a.getByRole('button',{name:'Create comparison',exact:true}).click();await mode('inquiry');assert.equal(await a.locator('#reasoning-inquiry-mode').getAttribute('aria-pressed'),'true');assert.deepEqual(errors,[]);
  const preview=await browser.newPage();preview.on('pageerror',e=>errors.push(e.message));await preview.goto(pathToFileURL(resolve('review/Harmonious-inquiry-preview.html')).href);await preview.locator('#reasoning-inquiry-mode[aria-pressed="true"]').waitFor();assert(await preview.locator('#compare-canvas').isVisible());assert.deepEqual(errors,[]);
  console.log('Inquiry foundation passed: peer mode, separate blank menus, node/edge inspection, parked Compare/Argument drafts, camera, existing Map access, unchanged data and mobile.');
}catch(error){for(const [i,ctx]of browser.contexts().entries())for(const p of ctx.pages()){await p.screenshot({path:`build/design-review/inquiry-failure-${i}.png`,fullPage:true});console.error((await p.locator('body').innerText()).slice(-6500));}console.error(errors);throw error;}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
