import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {alice,bob,memoryStore,seedActor,edit,view,addNode} from './accounts.test.mjs';
import {startAccountComparison} from '../worker/account-api.mjs';
import {validateAccountChanges} from '../worker/account-policy.mjs';
import {makeDiscussion,validateDiscussions,discussionHealth,discussionSourceSnapshot} from '../dist/discussion.mjs';
import {capturePremise,premiseChoices,premiseHealth,validatePremises} from '../dist/premise.mjs';
import {synchronizeIdeas,transferNodes,createOwnedMap} from '../dist/adoption.mjs';
import {makeDefinition,definitionReference,definitionReferenceText} from '../dist/definitions.mjs';
import {validateWorkspace} from '../dist/workspace.mjs';

export async function exercisePremises(store){
  const nodes={};
  for(const actor of [alice,bob])await edit(store,actor,ws=>{const map=ws.maps.find(m=>m.ownerId===actor.id);map.visibility='shared';for(const title of actor===alice?['Conclusion A','Premise B','Conclusion C','Different frame','A question']:['Other person’s position']){const node=addNode(ws,actor,title);node.kind=title==='A question'?'question':'position';nodes[title]={type:'node',mapId:map.id,nodeId:node.id};if(title==='Different frame')node.parent='goal';}synchronizeIdeas(ws,map);});
  const a=nodes['Conclusion A'],b=nodes['Premise B'],c=nodes['Conclusion C'],foreign=nodes['Other person’s position'];
  const thread=(await startAccountComparison(store,alice.id,{aMapId:a.mapId,bMapId:foreign.mapId})).comparisonThread;
  const entry=r=>({type:'entry',entryId:r.id});
  const save=async(actor,input,oldId=null)=>{let result;await edit(store,actor,ws=>{result=makeDiscussion(ws,{comparisonId:thread.id,...input},actor.id,ws.discussions.find(r=>r.id===oldId)||null);ws.discussions=ws.discussions.filter(r=>r.id!==result.id);ws.discussions.push(result);});return result;};
  const reasonInput=(ws,target,source)=>{const premise=capturePremise(ws,source);return {kind:'argument',action:'reason',target,premise,body:premise?.wording.title||'Unavailable'};};
  let ws=(await view(store,alice)).workspace;
  assert.equal(capturePremise(ws,nodes['A question']),null);
  const choices=premiseChoices(ws,{comparisonId:thread.id,target:a},alice.id);assert.deepEqual(new Set(choices.map(v=>v.node.id)),new Set([b.nodeId,c.nodeId]));assert(choices.every(v=>typeof v.path==='string'&&v.path.length));
  assert.deepEqual(premiseChoices(ws,{comparisonId:thread.id,target:foreign},alice.id),[]);
  const imported=structuredClone(ws),importedMap=imported.maps.find(m=>m.id===b.mapId),importedTitle='  Imported position  ';
  importedMap.nodes.find(n=>n.id===b.nodeId).title=importedTitle;synchronizeIdeas(imported,importedMap);validateWorkspace(imported);
  const importedReason=makeDiscussion(imported,{comparisonId:thread.id,...reasonInput(imported,a,b)},alice.id);assert.equal(importedReason.body,importedTitle,'A referenced imported title keeps its exact saved whitespace');
  imported.discussions.push(importedReason);const importedWithdrawal=makeDiscussion(imported,{...importedReason,status:'withdrawn'},alice.id,importedReason);assert.equal(importedWithdrawal.body,importedTitle);assert.equal(importedWithdrawal.history[0].body,importedTitle);
  assert.equal(makeDiscussion(imported,{comparisonId:thread.id,kind:'argument',action:'reason',target:a,body:'  Written reason  '},alice.id).body,'Written reason','Ordinary written contributions still trim surrounding whitespace');
  let definition,context;
  await edit(store,alice,w=>{definition=makeDefinition(w,{type:'definition',title:'Continuity',body:'An unbroken route.'},alice.id);w.definitions.push(definition);const refs=[definitionReference(definition)];context=makeDiscussion(w,{kind:'context',action:'context',target:b,definitionRefs:refs,body:definitionReferenceText(refs)},alice.id);w.discussions.push(context);});
  ws=(await view(store,alice)).workspace;
  let reason=await save(alice,reasonInput(ws,a,b));
  const initial=structuredClone(reason.premise);
  for(const timeScope of ['history','likely_future'])validatePremises({discussions:[{...reason,premise:{...initial,wording:{...initial.wording,timeScope}}}]});
  assert.equal(initial.contexts[0].definitionRefs[0].title,'Continuity');
  assert.equal(initial.wording.confidence,undefined);
  await assert.rejects(()=>save(alice,reasonInput(ws,a,b)),/already supports/);
  await assert.rejects(()=>save(alice,reasonInput(ws,a,a)),/support itself/);
  await assert.rejects(()=>save(alice,reasonInput(ws,entry(reason),b)),/repeat within/);
  await assert.rejects(()=>save(alice,reasonInput(ws,b,a)),/cycle/);
  await assert.rejects(()=>save(alice,reasonInput(ws,a,foreign)),/same comparison map and frame/);
  await assert.rejects(()=>save(alice,reasonInput(ws,a,nodes['Different frame'])),/same comparison map and frame/);
  await assert.rejects(()=>save(bob,reasonInput(ws,foreign,b)),/same comparison map and frame|saved premise wording/);
  const second=await save(alice,reasonInput(ws,c,b));assert.equal(second.premise.nodeId,b.nodeId,'A source may support a different conclusion');
  const written=await save(alice,{kind:'argument',action:'reason',target:entry(reason),body:'A further written reason.'});
  await assert.rejects(()=>save(alice,reasonInput(ws,entry(written),b)),/repeat within/);
  const challenge=await save(bob,{kind:'argument',action:'fallacy',target:entry(written),body:'The inference is not established.'});
  const response=await save(alice,{kind:'reply',action:'reply',target:entry(challenge),layer:'arguments',body:'This response makes a separate claim.'});
  const responseReason=await save(alice,reasonInput(ws,entry(response),b));assert(responseReason,'Contextual ancestry resolves scope without mistaking responses for support dependencies');
  const foreignChallenge=await save(alice,{kind:'argument',action:'challenge',target:foreign,body:'The claimed benefit may not follow.'});
  const foreignResponse=await save(alice,{kind:'reply',action:'reply',target:entry(foreignChallenge),layer:'arguments',body:'Here is my further response about your claim.'});
  ws=(await view(store,alice)).workspace;
  assert(premiseChoices(ws,{comparisonId:thread.id,target:entry(foreignResponse)},alice.id).some(v=>v.node.id===b.nodeId),'A response anchored on the other map uses the author’s map in the corresponding frame');
  await save(alice,reasonInput(ws,entry(foreignResponse),b));
  ws=(await view(store,bob)).workspace;
  assert.equal(ws.definitions.length,0);assert.equal(ws.discussions.find(r=>r.id===reason.id).premise.contexts[0].definitionRefs[0].body,'An unbroken route.');
  assert.deepEqual(validateWorkspace(structuredClone(ws)),ws,'Pinned source survives a portable round trip');
  assert.deepEqual(discussionSourceSnapshot(ws,entry(reason)).wording.premise,initial);
  await edit(store,alice,w=>{const old=w.definitions.find(d=>d.id===definition.id);w.definitions=w.definitions.map(d=>d.id===old.id?makeDefinition(w,{title:'Continuity',body:'PRIVATE UNINVOKED UPDATE'},alice.id,old):d);});
  ws=(await view(store,bob)).workspace;assert(!JSON.stringify(ws).includes('PRIVATE UNINVOKED UPDATE'));assert.equal(discussionHealth(ws,challenge).state,'current');
  await edit(store,alice,w=>{w.maps.find(m=>m.id===b.mapId).nodes.find(n=>n.id===b.nodeId).confidence=73.5;});
  ws=(await view(store,alice)).workspace;assert.equal(premiseHealth(ws,reason).state,'current');assert.equal(discussionHealth(ws,challenge).state,'current');
  const stale=makeDiscussion(ws,{comparisonId:thread.id,...reasonInput(ws,a,c)},alice.id);
  await edit(store,alice,w=>{const map=w.maps.find(m=>m.id===b.mapId);map.nodes.find(n=>n.id===b.nodeId).summary='UPDATED SOURCE SUMMARY';map.nodes.find(n=>n.id===c.nodeId).details='CHANGED AFTER PREVIEW';synchronizeIdeas(w,map);});
  ws=(await view(store,bob)).workspace;
  assert.equal(discussionHealth(ws,reason).state,'changed');assert.equal(discussionHealth(ws,challenge).upstreamChanged,true);
  assert.deepEqual(ws.discussions.find(r=>r.id===reason.id).premise,initial,'A source edit does not silently rewrite the saved reason');
  const changedSnapshot=await store.snapshot();
  assert.throws(()=>validateAccountChanges(changedSnapshot,alice.id,[{kind:'discussion',id:stale.id,expectedRevision:0,value:stale}]),/source position changed/i,'A stale preview fails at the account boundary');
  ws=(await view(store,alice)).workspace;
  const forged=makeDiscussion(ws,{comparisonId:thread.id,...reasonInput(ws,a,c)},alice.id);forged.premise.wording.title='FORGED SOURCE';forged.body='FORGED SOURCE';
  assert.throws(()=>validateAccountChanges(changedSnapshot,alice.id,[{kind:'discussion',id:forged.id,expectedRevision:0,value:forged}]),/source position changed/i);
  const forgedContext=structuredClone(forged);forgedContext.premise=capturePremise(ws,c);forgedContext.body=forgedContext.premise.wording.title;forgedContext.premise.contexts=structuredClone(initial.contexts);
  assert.throws(()=>validateAccountChanges(changedSnapshot,alice.id,[{kind:'discussion',id:forgedContext.id,expectedRevision:0,value:forgedContext}]),/source position changed/i,'An unrelated invoked definition cannot be copied into source context');
  await assert.rejects(()=>save(alice,{...reason,body:'Independent duplicate wording'},reason.id),/saved premise wording/);
  await assert.rejects(()=>save(alice,{...reason,premise:capturePremise(ws,c),body:'Conclusion C'},reason.id),/preserve its source position/);
  await assert.rejects(()=>save(alice,{...reason,premise:null},reason.id),/saved premise|source position/);
  const refreshedInput={...reason,premise:capturePremise(ws,b)};refreshedInput.body=refreshedInput.premise.wording.title;
  const staged=makeDiscussion(ws,refreshedInput,alice.id,reason),restaged=makeDiscussion({...ws,discussions:ws.discussions.map(r=>r.id===reason.id?staged:r)},{...staged},alice.id,staged);
  const reasonRow=changedSnapshot.records.find(r=>r.id===reason.id&&r.kind==='discussion'),changeFor=value=>[{kind:'discussion',id:value.id,expectedRevision:reasonRow.revision,value}];
  validateAccountChanges(changedSnapshot,alice.id,changeFor(restaged));
  const inventedHistory=structuredClone(restaged);inventedHistory.history.at(-1).premise.wording.summary='FABRICATED INTERMEDIATE SOURCE';
  assert.throws(()=>validateAccountChanges(changedSnapshot,alice.id,changeFor(inventedHistory)),/New premise history/,'A correct final source cannot hide fabricated intermediate source wording');
  assert.throws(()=>validateAccountChanges(changedSnapshot,alice.id,changeFor({...inventedHistory,premise:reason.premise,body:reason.body})),/New premise history/,'Keeping the current saved premise also cannot hide fabricated history');
  const savedThenCurrent=structuredClone(restaged);savedThenCurrent.history.at(-1).premise=structuredClone(reason.premise);savedThenCurrent.history.at(-1).body=reason.body;
  validateAccountChanges(changedSnapshot,alice.id,changeFor(savedThenCurrent));
  reason=await save(alice,refreshedInput,reason.id);
  assert.deepEqual(reason.history[0].premise,initial);assert.equal(reason.premise.wording.summary,'UPDATED SOURCE SUMMARY');
  assert.deepEqual(reason.sourceSnapshots,reason.history[0].sourceSnapshots,'Refresh preserves the original conclusion snapshot');
  ws=(await view(store,bob)).workspace;assert.equal(premiseHealth(ws,reason).state,'current');assert.equal(discussionHealth(ws,challenge).state,'changed','Challenges retain their original premise version after a refresh');
  await edit(store,alice,w=>{const old=w.discussions.find(r=>r.id===context.id);context=makeDiscussion(w,{...old,status:'withdrawn'},alice.id,old);w.discussions=w.discussions.map(r=>r.id===context.id?context:r);});
  ws=(await view(store,alice)).workspace;assert.equal(premiseHealth(ws,reason).state,'changed','Withdrawing an invoked context flags pinned source context');
  assert.equal(reason.premise.contexts.length,1);
  reason=await save(alice,{...reason,premise:capturePremise(ws,b)},reason.id);assert.equal(reason.premise.contexts.length,0);assert.equal(reason.history[0].premise.contexts.length,1);
  let linkedId;
  await edit(store,alice,w=>{linkedId=transferNodes(w,{sourceMapId:foreign.mapId,targetMapId:a.mapId,nodeIds:[foreign.nodeId],mode:'linked'}).added[0];});
  ws=(await view(store,alice)).workspace;
  const linkedTarget={mapId:a.mapId,nodeId:linkedId};let linkedReason=await save(alice,reasonInput(ws,a,linkedTarget));
  const previousIdea=linkedReason.premise.ideaId;
  await edit(store,alice,w=>{const map=w.maps.find(m=>m.id===a.mapId);map.nodes.find(n=>n.id===linkedId).title='My adapted premise';synchronizeIdeas(w,map);});
  ws=(await view(store,alice)).workspace;const linkedCurrent=capturePremise(ws,linkedTarget);assert.notEqual(linkedCurrent.ideaId,previousIdea);
  linkedReason=await save(alice,{...linkedReason,premise:linkedCurrent,body:linkedCurrent.wording.title},linkedReason.id);assert.equal(linkedReason.history[0].premise.ideaId,previousIdea,'Refreshing a detached linked node preserves its earlier identity in history');
  let secondMap;
  await edit(store,alice,w=>{secondMap=createOwnedMap(w,{name:'My second map',ownerId:alice.id});secondMap.visibility='shared';const source=w.maps.find(m=>m.id===a.mapId).nodes.find(n=>n.id===c.nodeId);secondMap.nodes.push({...structuredClone(source),id:'own-second-position',ideaId:undefined,ideaVersion:undefined});synchronizeIdeas(w,secondMap);});
  const ownThread=(await startAccountComparison(store,alice.id,{aMapId:a.mapId,bMapId:secondMap.id})).comparisonThread;
  ws=(await view(store,alice)).workspace;
  assert(premiseChoices(ws,{comparisonId:ownThread.id,target:a},alice.id).every(v=>v.map.id===a.mapId),'Two owned maps retain the anchored map as the source');
  await edit(store,alice,w=>{const map=w.maps.find(m=>m.id===b.mapId);map.nodes=map.nodes.filter(n=>n.id!==b.nodeId);});
  ws=(await view(store,bob)).workspace;assert.equal(premiseHealth(ws,reason).state,'unavailable');assert.equal(discussionHealth(ws,challenge).state,'unavailable');
  assert.equal(ws.discussions.find(r=>r.id===reason.id).premise.wording.title,'Premise B','Deleting a source leaves the recorded claim readable');
  assert.deepEqual(validateWorkspace(structuredClone(ws)),ws,'Historical premises need no live source placement');
  await assert.rejects(()=>save(alice,{...reason,referenceUrl:'https://example.org/changed'},reason.id),/available/);
  reason=await save(alice,{...reason,status:'withdrawn'},reason.id);assert.equal(reason.status,'withdrawn');assert.equal(reason.history.at(-1).status,'active');
  const snapshot=await store.snapshot(),row=snapshot.records.find(r=>r.id===reason.id&&r.kind==='discussion');
  const request=value=>[{kind:'discussion',id:value.id,expectedRevision:row.revision,value}];
  const without={...reason};delete without.premise;
  assert.throws(()=>validateAccountChanges(snapshot,alice.id,request(without)),/preserve whether/,'An older-style payload cannot erase a saved premise');
  assert.throws(()=>validateAccountChanges(snapshot,bob.id,request(reason)),e=>e.status===403);
  for(const premise of [null,{...initial,extra:'unexpected'}])assert.throws(()=>validatePremises({discussions:[{...reason,history:[],version:1,premise}]}),/saved premise/);
  const historyTamper=structuredClone(reason);historyTamper.history[0].premise.nodeId='replacement';assert.throws(()=>validateDiscussions({...ws,discussions:[...ws.discussions.filter(r=>r.id!==reason.id),historyTamper]}),/preserve its source position/);
  const nonreason={...reason,id:'not-a-reason',kind:'inquiry',action:'question',status:'active',history:[],version:1};assert.throws(()=>validatePremises({discussions:[nonreason]}),/saved premise/);
  const longCycle=Array.from({length:2000},(_,i)=>({...reason,id:`cycle-${i}`,target:{type:'node',mapId:a.mapId,nodeId:`virtual-${i}`},status:'active',history:[],version:1,premise:{...initial,nodeId:`virtual-${(i+1)%2000}`},body:initial.wording.title}));
  assert.throws(()=>validatePremises({discussions:longCycle}),/cycle/,'Long support dependency cycles are checked without recursion');
  await edit(store,alice,w=>{w.maps.find(m=>m.id===a.mapId).visibility='private';});
  ws=(await view(store,bob)).workspace;assert(!ws.discussions.some(r=>r.id===reason.id));assert(!JSON.stringify(ws).includes('UPDATED SOURCE SUMMARY'),'Revoking map access also removes pinned source wording');
  console.log('Pinned premise ownership, scope, context privacy, exact refresh, histories, source health, account tamper rejection, duplicates, cycles and deletion passed.');
}

if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const store=memoryStore();for(const actor of [alice,bob])await seedActor(store,actor);await exercisePremises(store);}
