import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {alice,bob,memoryStore,seedActor,edit,view,addNode} from './accounts.test.mjs';
import {startAccountComparison} from '../worker/account-api.mjs';
import {validateAccountChanges} from '../worker/account-policy.mjs';
import {makeDiscussion,validateDiscussions,discussionHealth,isReason,isChallenge,canExplainReasoning} from '../dist/discussion.mjs';
import {makeDefinition,definitionReference} from '../dist/definitions.mjs';
import {conversationAnchor,conversationGroups,reasoningBranch,selectReasoningEntries,challengeState} from '../dist/conversation-tree.mjs';
import {synchronizeIdeas,createOwnedMap} from '../dist/adoption.mjs';
import {stableJSON} from '../dist/account-model.mjs';
import {validateWorkspace} from '../dist/workspace.mjs';

export async function exerciseReasoning(store){
  for(const actor of [alice,bob])await edit(store,actor,w=>{w.maps.find(m=>m.ownerId===actor.id).visibility='shared';addNode(w,actor,`${actor.name}'s reasoning position`);});
  let ws=(await view(store,alice)).workspace;
  const own=ws.maps.find(m=>m.ownerId===alice.id),other=ws.maps.find(m=>m.ownerId===bob.id);
  const target={type:'node',mapId:own.id,nodeId:own.nodes.at(-1).id},otherTarget={type:'node',mapId:other.id,nodeId:other.nodes.at(-1).id};
  const thread=(await startAccountComparison(store,alice.id,{aMapId:own.id,bMapId:other.id})).comparisonThread;
  const save=async(actor,input,oldId=null)=>{let result;await edit(store,actor,w=>{result=makeDiscussion(w,{comparisonId:thread.id,...input},actor.id,w.discussions.find(r=>r.id===oldId)||null);w.discussions=w.discussions.filter(r=>r.id!==result.id);w.discussions.push(result);});return result;};
  const entry=r=>({type:'entry',entryId:r.id}),inference=r=>({type:'inference',entryId:r.id});
  const reasonInput={kind:'argument',action:'reason',target,body:'A continuous protected route removes exposed crossings.'};
  let definition;
  await edit(store,alice,w=>{definition=makeDefinition(w,{type:'standard',title:'Safety',body:'Compare the rate of serious injuries per trip.'},alice.id);w.definitions.push(definition);});
  const ref=definitionReference(definition);
  let reason=await save(alice,{...reasonInput,definitionRefs:[ref],referenceUrl:'https://example.org/route-study'});
  const further=await save(alice,{...reasonInput,target:entry(reason),body:'The route connects both sides of each junction.'});
  const challenge=await save(bob,{kind:'argument',action:'inference',target:inference(further),body:'Connecting a junction does not establish that its crossing is protected.'});
  const statementChallenge=await save(bob,{kind:'argument',action:'challenge',target:entry(reason),body:'One crossing may still be exposed.'});
  const response=await save(alice,{kind:'reply',action:'reply',target:entry(challenge),layer:'arguments',body:'The junction design also separates crossing traffic.',definitionRefs:[ref]});
  const responseReason=await save(alice,{...reasonInput,target:entry(response),body:'Turning vehicles receive a separate signal phase.'});
  await save(bob,{kind:'argument',action:'challenge',target:entry(responseReason),body:'Does that apply during the evening signal cycle?'});
  const inferenceSnapshot=challenge.sourceSnapshots[0],original=stableJSON(inferenceSnapshot);
  assert.equal(inferenceSnapshot.wording.reason.target.entryId,further.id);
  assert.equal(inferenceSnapshot.wording.conclusion.target.entryId,reason.id);
  assert.equal(inferenceSnapshot.wording.conclusion.definitions[0].version,1);
  assert.equal(inferenceSnapshot.wording.conclusion.wording.body,reason.body);
  assert.equal(inferenceSnapshot.wording.conclusion.sourceSnapshots,undefined,'Inference endpoints never recursively embed their own source history');
  assert(isReason(reason));assert(!isChallenge(reason));assert(isChallenge(challenge));assert.equal(challengeState([],reason),null);
  ws=(await view(store,bob)).workspace;
  assert(ws.discussions.some(r=>r.id===reason.id),'Reasons are shared in the existing Comparison');
  assert(!ws.definitions.length,'A participant receives invoked definition snapshots, not the author library');
  assert.equal(ws.discussions.find(r=>r.id===response.id).definitionRefs[0].body,ref.body);
  assert.deepEqual(validateWorkspace(JSON.parse(JSON.stringify(ws))),ws,'New reasoning survives portable round trip');
  assert.deepEqual(conversationAnchor(ws.discussions,challenge),target);
  const group=conversationGroups(ws.discussions).find(g=>g.target.nodeId===target.nodeId);
  assert.equal(group.reasons,3);assert.equal(group.challenges,3);assert.equal(group.openChallenges,3);
  const branch=reasoningBranch(ws.discussions,target);
  assert.equal(branch.connections.length,3);assert.deepEqual(branch.connections.find(c=>c.reasonId===further.id).target,inference(further));
  const shuffled=reasoningBranch([...ws.discussions].reverse(),target),order=shuffled.entries.map(r=>r.id);
  for(const r of shuffled.entries)if(order.includes(r.target.entryId))assert(order.indexOf(r.target.entryId)<order.indexOf(r.id),'Argument display remains parent-first after edits or reordered database rows');
  const small=selectReasoningEntries(shuffled,3),shown=new Set(small.entries.map(r=>r.id));
  assert.equal(small.entries.length,3);assert.equal(small.hiddenCount,shuffled.entries.length-3);
  for(const r of small.entries)if(order.includes(r.target.entryId))assert(shown.has(r.target.entryId),'Visible caps never retarget a child by hiding its parent');
  const focused=selectReasoningEntries(shuffled,5,responseReason.id);assert(focused.entries.some(r=>r.id===responseReason.id));assert.equal(focused.focusOmitted,false);
  assert.equal(selectReasoningEntries(shuffled,3,responseReason.id).focusOmitted,true,'A chain larger than the cap is explicitly reported');
  const question={...challenge,id:'context-question',kind:'inquiry',action:'question',target},challengeQuestion={...challenge,id:'question-challenge',target:{type:'entry',entryId:'context-question'}};
  const contextual=reasoningBranch([question,challengeQuestion],target);assert.deepEqual(contextual.entries.map(r=>r.id),['context-question','question-challenge']);assert(contextual.placeholders.some(p=>p.entryId===question.id&&p.contextOnly));
  assert(canExplainReasoning(ws,otherTarget,bob.id));assert(!canExplainReasoning(ws,target,bob.id));
  assert(!canExplainReasoning(ws,entry(challenge),bob.id));assert(!canExplainReasoning(ws,inference(reason),alice.id));
  await assert.rejects(()=>save(bob,reasonInput),/own position/);
  await assert.rejects(()=>save(alice,{...reasonInput,target:{type:'node',mapId:own.id,nodeId:own.nodes.find(n=>n.parent===null).id}}),/own position/);
  await assert.rejects(()=>save(alice,{...reasonInput,target:{type:'edge',mapId:own.id,edgeId:`structure:${target.nodeId}`}}),/own position/);
  await assert.rejects(()=>save(bob,{...reasonInput,target:entry(reason)}),/own position/);
  await assert.rejects(()=>save(bob,{...reasonInput,target:entry(challenge)}),/own position/);
  await assert.rejects(()=>save(alice,{...reasonInput,target:inference(reason)}),/own position/);
  await assert.rejects(()=>save(bob,{kind:'argument',action:'challenge',target:inference(challenge),body:'Invalid inference'}),/source changed|reasoning connection/i);
  for(const actor of [alice,bob])for(const action of ['resolve','reopen','accept','maintain'])await assert.rejects(()=>save(actor,{kind:'reply',action,target:entry(reason),layer:'arguments',body:'This is not a challenge.'}),/Choose a challenge/);
  await assert.rejects(()=>save(alice,{kind:'reply',action:'resolve',target:entry(challenge),layer:'arguments',body:'I cannot resolve your challenge.'}),/own response or resolution/);
  await save(alice,{kind:'reply',action:'accept',target:entry(challenge),layer:'arguments',body:'I accept this needs clarification.'});
  assert.equal(challengeState((await view(store,bob)).workspace.discussions,challenge),'Open');
  await save(bob,{kind:'reply',action:'resolve',target:entry(challenge),layer:'arguments',body:'The response answers this objection.'});
  assert.equal(challengeState((await view(store,alice)).workspace.discussions,challenge),'Resolved by challenger');
  await assert.rejects(()=>save(alice,{...reason,action:'challenge'},reason.id),/identity|role/);
  await assert.rejects(()=>save(bob,{...statementChallenge,action:'reason'},statementChallenge.id),/identity|role/);
  await assert.rejects(()=>save(alice,{...reasonInput,definitionRefs:[{...ref,body:'Invented standard'}]}),/available version/);
  await assert.rejects(()=>save(bob,{kind:'argument',action:'challenge',target,body:'I cannot invoke Alice’s private library.',definitionRefs:[ref]}),/referenced definitions|available version/);
  await assert.rejects(()=>save(alice,{...reasonInput,definitionRefs:[ref,ref]}),/referenced definitions|definition references/);
  await assert.rejects(()=>save(alice,{kind:'inquiry',action:'question',target:otherTarget,body:'Inquiry references are not part of this increment.',definitionRefs:[ref]}),/referenced definitions/);
  await edit(store,alice,w=>{const old=w.definitions.find(d=>d.id===definition.id);definition=makeDefinition(w,{title:'Safety',body:'PRIVATE REVISED STANDARD: include long-term health.'},alice.id,old);w.definitions=w.definitions.map(d=>d.id===definition.id?definition:d);});
  ws=(await view(store,bob)).workspace;assert(!JSON.stringify(ws).includes('PRIVATE REVISED STANDARD'));assert.equal(discussionHealth(ws,challenge).state,'current');
  const staleChallenge=makeDiscussion(ws,{comparisonId:thread.id,kind:'argument',action:'challenge',target:inference(reason),body:'An older draft based on the earlier reason.'},bob.id);
  reason=await save(alice,{...reason,body:'A continuous protected route removes the currently exposed crossings.',definitionRefs:[definitionReference(definition)]},reason.id);
  ws=(await view(store,bob)).workspace;assert.equal(discussionHealth(ws,challenge).state,'changed');assert.equal(stableJSON(ws.discussions.find(r=>r.id===challenge.id).sourceSnapshots[0]),original);
  const changedSnapshot=await store.snapshot();
  assert.throws(()=>validateAccountChanges(changedSnapshot,bob.id,[{kind:'discussion',id:staleChallenge.id,expectedRevision:0,value:staleChallenge}]),/source changed/i,'Saving a stale inference draft cannot silently capture newer wording');
  assert.equal(reason.history[0].definitionRefs[0].version,1,'Editing preserves the exact invoked version in history');
  assert.equal(reason.definitionRefs[0].version,2);
  const refreshed=await save(bob,{...challenge,reviewSources:true},challenge.id);
  assert.equal(refreshed.sourceSnapshots[0].wording.conclusion.definitions[0].version,1);
  assert.equal(refreshed.reviewedSources[0].wording.conclusion.definitions[0].version,2);
  await edit(store,alice,w=>{const map=w.maps.find(m=>m.id===own.id);map.nodes.find(n=>n.id===target.nodeId).details='The position now includes junctions outside the proposed route.';synchronizeIdeas(w,map);});
  ws=(await view(store,bob)).workspace;assert.equal(discussionHealth(ws,refreshed).state,'changed');assert.equal(discussionHealth(ws,refreshed).upstreamChanged,true,'Upstream changes remain visible without recursive source snapshots');
  const withdrawn=await save(alice,{...reason,status:'withdrawn'},reason.id);
  ws=(await view(store,bob)).workspace;assert.equal(discussionHealth(ws,refreshed).state,'unavailable');assert.equal(stableJSON(refreshed.sourceSnapshots[0]),original);
  const surviving=reasoningBranch(ws.discussions,target);assert(surviving.entries.some(r=>r.id===reason.id&&r.status==='withdrawn'));assert(surviving.placeholders.some(p=>p.entryId===reason.id&&p.withdrawn));assert(surviving.entries.some(r=>r.id===challenge.id),'Withdrawing a parent keeps descendants attached through a historical placeholder');
  assert.equal(conversationGroups(ws.discussions).find(g=>g.target.nodeId===target.nodeId).reasons,2,'The withdrawn ancestor is not counted as an active reason');
  await assert.rejects(()=>save(bob,{kind:'argument',action:'challenge',target:entry(withdrawn),body:'Cannot start on a withdrawn statement.'}),/withdrawn|available/);
  await assert.rejects(()=>save(bob,{kind:'argument',action:'challenge',target:inference(further),body:'Cannot start on a withdrawn conclusion.'}),/withdrawn|available/);
  await assert.rejects(()=>save(bob,{...statementChallenge,body:'Active edit after target withdrawal.'},statementChallenge.id),/available/);
  await assert.rejects(()=>save(bob,{...refreshed,body:'Active edit after upstream withdrawal.'},refreshed.id),/available/);
  for(const change of [{body:'A different challenge.'},{action:'fallacy'},{referenceUrl:'https://example.org/changed-reference'}])await assert.rejects(()=>save(bob,{...statementChallenge,...change,status:'withdrawn'},statementChallenge.id),/available/,'Withdrawal cannot disguise changes to authored content');
  const withdrawnChild=await save(bob,{...statementChallenge,status:'withdrawn'},statementChallenge.id);
  assert.equal(withdrawnChild.status,'withdrawn');assert.equal(withdrawnChild.body,statementChallenge.body);assert.equal(stableJSON(withdrawnChild.sourceSnapshots),stableJSON(statementChallenge.sourceSnapshots));assert.deepEqual(withdrawnChild.history.at(-1),(({history,...rest})=>rest)(statementChallenge),'Withdrawing a child retains its prior contribution exactly');
  const withdrawnInference=await save(bob,{...refreshed,status:'withdrawn'},refreshed.id);assert.equal(withdrawnInference.status,'withdrawn','Inference-targeted challenges can also be withdrawn after a conclusion withdrawal');
  await save(alice,{...withdrawn,status:'active'},withdrawn.id);
  let extraMap;
  await edit(store,alice,w=>{extraMap=createOwnedMap(w,{name:'Separate reasoning discussion',ownerId:alice.id,mapType:'personal'});extraMap.visibility='shared';});
  const otherThread=(await startAccountComparison(store,alice.id,{aMapId:extraMap.id,bMapId:other.id})).comparisonThread;
  await assert.rejects(()=>save(bob,{comparisonId:otherThread.id,kind:'argument',action:'challenge',target:inference(further),body:'Cross-comparison inference.'}),/same comparison/);
  ws=(await view(store,alice)).workspace;
  const missing={...statementChallenge,id:'missing-parent',target:{type:'inference',entryId:'not-found'},sourceSnapshots:undefined};
  assert.throws(()=>validateDiscussions({...ws,discussions:[...ws.discussions,missing]}),/same comparison/);
  const badInference={...statementChallenge,id:'not-a-reason',target:inference(statementChallenge),sourceSnapshots:undefined};
  assert.throws(()=>validateDiscussions({...ws,discussions:[...ws.discussions,badInference]}),/reasoning connection/);
  const self={...reason,id:'self-reason',target:{type:'entry',entryId:'self-reason'},history:[],version:1,sourceSnapshots:undefined};
  assert.throws(()=>validateDiscussions({...ws,discussions:[...ws.discussions,self]}),/cycle/);
  const chain=Array.from({length:2000},(_,i)=>({...self,id:`long-${i}`,target:{type:'entry',entryId:`long-${(i+1)%2000}`}}));
  assert.throws(()=>validateDiscussions({...ws,discussions:[...ws.discussions,...chain]}),/cycle/,'Long imported chains are checked iteratively');
  const snapshot=await store.snapshot(),saved=snapshot.records.find(r=>r.id===reason.id&&r.kind==='discussion');
  assert.throws(()=>validateAccountChanges(snapshot,bob.id,[{kind:'discussion',id:reason.id,expectedRevision:saved.revision,value:{...saved.value,body:'Foreign rewrite'}}]),e=>e.status===403);
  await edit(store,alice,w=>{w.maps.find(m=>m.id===own.id).visibility='private';});
  ws=(await view(store,bob)).workspace;assert(!ws.discussions.some(r=>[reason.id,further.id,challenge.id,response.id].includes(r.id)));assert(!JSON.stringify(ws).includes(ref.body),'Revoking map access also removes reason and inference snapshots');
  await edit(store,alice,w=>{w.maps.find(m=>m.id===own.id).visibility='shared';});
  console.log('Reason chains, statement/inference targets, bounded history, definitions, outcomes, ownership, cycle checks and privacy passed.');
}

if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const store=memoryStore();for(const actor of [alice,bob])await seedActor(store,actor);await exerciseReasoning(store);}
