import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {alice,bob,memoryStore,seedActor,edit,addNode,view} from './accounts.test.mjs';
import {accountWorkspace,saveAccountChanges,startAccountComparison} from '../worker/account-api.mjs';
import {makeDiscussion} from '../dist/discussion.mjs';
import {synchronizeIdeas} from '../dist/adoption.mjs';
import {isReflection,isDisagreementPoint,isReflectionOutcome} from '../dist/reflection.mjs';
import {challengeState} from '../dist/conversation-tree.mjs';

// Disposable two-account UI exercising the real read/save API, including lost ACKs.
const playwright=process.env.HARMONIOUS_PLAYWRIGHT;if(!playwright)throw Error('Set HARMONIOUS_PLAYWRIGHT.');
const {chromium}=await import(pathToFileURL(playwright)),store=memoryStore(),ids={};
for(const actor of [alice,bob]){await seedActor(store,actor);await edit(store,actor,ws=>{const map=ws.maps.find(m=>m.ownerId===actor.id);map.visibility='shared';map.name=actor.name+' reflection map';for(const title of actor===alice?['Evening meeting','Quiet source without reasons','Nested source']:['Daytime meeting']){const n=addNode(ws,actor,title);n.kind='position';n.parent=title==='Nested source'?ids['Evening meeting']:'status';n.summary='Original source explanation for '+title;ids[title]=n.id;}synchronizeIdeas(ws,map);});}
const initial=(await view(store,alice)).workspace,aMap=initial.maps.find(m=>m.ownerId===alice.id),bMap=initial.maps.find(m=>m.ownerId===bob.id),at={type:'node',mapId:aMap.id,nodeId:ids['Evening meeting']};
const {comparisonThread:thread}=await startAccountComparison(store,alice.id,{aMapId:aMap.id,bMapId:bMap.id});
const seed=async(actor,input)=>{let result;await edit(store,actor,ws=>{result=makeDiscussion(ws,{comparisonId:thread.id,...input},actor.id);ws.discussions.push(result);});return result;};
const reason=await seed(alice,{kind:'argument',action:'reason',target:at,body:'Most respondents prefer evening.'}),child=await seed(alice,{kind:'argument',action:'reason',target:{type:'entry',entryId:reason.id},body:'Eighteen replies chose the evening slot.'}),challenge=await seed(bob,{kind:'argument',action:'challenge',target:{type:'inference',entryId:reason.id},body:'Respondents may not represent all members.'});
const originalMaps=structuredClone((await view(store,alice)).workspace.maps);let loseNext=false,failBeforeNext=false,raceNextOutcome=false;const writes=[],errors=[],uncertain=[];
const json=(res,status,value)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(value));};
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),actor=req.headers['x-test-actor']==='bob'?bob:alice;if(url.pathname.startsWith('/api/')){let raw='';for await(const chunk of req)raw+=chunk;const input=raw?JSON.parse(raw):null;if(url.pathname==='/api/session'){json(res,200,{configured:true,actor,signup:{mode:'public'}});return;}if(url.pathname==='/api/comparisons'){json(res,200,await startAccountComparison(store,actor.id,input));return;}if(url.pathname==='/api/workspace'&&req.method==='PUT'){if(failBeforeNext&&input.changes.some(c=>c.kind==='discussion'&&isReflection(c.value))){failBeforeNext=false;uncertain.push(input.changes);json(res,503,{error:'The write has not been acknowledged.'});return;}if(raceNextOutcome){const outcome=input.changes.find(c=>c.kind==='discussion'&&isReflectionOutcome(c.value))?.value;if(outcome){raceNextOutcome=false;await seed(actor,{kind:'reflection',action:'outcome',layer:'arguments',target:outcome.target,body:'Another window already saved my assessment.',reflection:{result:'more_work',nextStep:''}});}}const result=await saveAccountChanges(store,actor.id,input.changes);writes.push(input.changes);if(loseNext&&input.changes.some(c=>c.kind==='discussion'&&isReflection(c.value))){loseNext=false;json(res,503,{error:'The annotation acknowledgment was lost.'});return;}json(res,200,result);return;}json(res,200,await accountWorkspace(store,actor));return;}const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!/^[a-z0-9.-]+$/.test(name)){res.writeHead(404);res.end();return;}let content=await readFile(resolve('dist',name),'utf8');if(name==='index.html')content=content.replace('src="./app.mjs"','src="./beta-boot.mjs"').replace('</head>','<link rel="stylesheet" href="./accounts.css"></head>');res.setHeader('content-type',name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'text/javascript');res.end(content);}catch(e){json(res,e.status||500,{error:e.message});}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,channel:process.env.HARMONIOUS_BROWSER||'msedge'});
try{
  await mkdir('build/design-review',{recursive:true});const pages=[];for(const actor of ['alice','bob']){const ctx=await browser.newContext({viewport:{width:1440,height:1000},extraHTTPHeaders:{'x-test-actor':actor}}),page=await ctx.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));pages.push(page);}const [a,b]=pages,pop=p=>p.locator('.discussion-popover'),action=(p,name)=>pop(p).getByRole('button',{name,exact:true}).click(),close=async p=>{if(await pop(p).isVisible())await action(p,'Close');},saved=p=>p.waitForFunction(()=>document.getElementById('storage-status')?.textContent.includes('All changes saved'));
  const records=async()=>((await view(store,alice)).workspace.discussions),byBody=async body=>(await records()).find(r=>r.body===body);
  let nav=0;const expand=async p=>{await p.locator('.comparison-view-options>summary').click();for(const side of ['a','b'])await p.locator('#compare-all-'+side).click();await p.locator('.comparison-view-options>summary').click();};const load=async p=>{await p.goto(origin+'/?load='+(++nav)+'#comparison='+thread.id);await expand(p);};
  const node=async(p,title)=>{await close(p);const button=p.locator('#compare-canvas .node-main').filter({has:p.getByText(title,{exact:true})}).first();await button.focus();await p.keyboard.press('Enter');};
  const card=async(p,id)=>{await close(p);const button=p.locator(`.reasoning-card[data-entry="${id}"] .reasoning-main`);await button.focus();await p.keyboard.press('Enter');};
  const follow=async p=>{await node(p,'Evening meeting');await p.locator('#reasoning-argument-mode').click();await close(p);const counter=p.getByRole('button',{name:/reasons attached to Evening meeting/}).first();await counter.click();};
  const find=async(p,query)=>{await close(p);await p.getByRole('button',{name:'Find in argument',exact:true}).click();const search=p.locator('.reasoning-search');await search.getByRole('searchbox',{name:'Search argument'}).fill(query);await search.getByRole('button',{name:'Show on map',exact:true}).click();};
  const submitPoint=async(p,body,{category='',retry=false}={})=>{await action(p,'Mark point of disagreement');await p.locator('#reflection-body').fill(body);if(category){await pop(p).getByText('Type of disagreement (optional)',{exact:true}).click();await p.locator('#reflection-category').selectOption(category);}if(retry)loseNext=true;await action(p,'Save point');if(!retry)await pop(p).getByRole('button',{name:'Record my outcome',exact:true}).waitFor();return byBody(body);};
  const noAnnotationCards=async p=>{const annotations=(await records()).filter(isReflection);for(const r of annotations)assert.equal(await p.locator(`.reasoning-card[data-entry="${r.id}"]`).count(),0,'Annotations never become graph cards');};

  await load(a);await node(a,'Daytime meeting');assert.equal(await pop(a).getByRole('button',{name:'Mark point of disagreement',exact:true}).count(),0);
  await action(a,'Ask');await a.locator('#discussion-action').selectOption('change_mind');assert.equal(await a.locator('#discussion-body').inputValue(),'What would change your mind?');await a.locator('#discussion-body').fill('What evidence about participation would change your mind?');await a.locator('#discussion-action').selectOption('example');assert.equal(await a.locator('#discussion-body').inputValue(),'What evidence about participation would change your mind?','Preset changes preserve edited questions');await a.locator('#discussion-action').selectOption('change_mind');await action(a,'Send question');await saved(a);const inquiry=await byBody('What evidence about participation would change your mind?');assert.equal(inquiry.action,'question');assert.equal(inquiry.kind,'inquiry');
  await load(b);await node(b,'Daytime meeting');await close(b);await b.getByRole('button',{name:'Conversations',exact:true}).click();await pop(b).locator('.discussion-list-item').filter({hasText:'Question'}).click();await action(b,'Answer');await b.locator('#discussion-body').fill('A representative attendance survey could change my mind.');await action(b,'Post response');await saved(b);

  // Point-only sources need no existing argument and never draw an extra card.
  await node(a,'Quiet source without reasons');await a.locator('#reasoning-argument-mode').click();await action(a,'Mark point of disagreement');await a.locator('#reflection-body').fill('The availability estimate is the point we differ on.');await pop(a).getByText('Type of disagreement (optional)',{exact:true}).click();await a.locator('#reflection-category').selectOption('facts');const camera=await a.locator('#compare-canvas .comparison-world').getAttribute('style');await a.locator('#reasoning-compare-mode').click();assert.equal(await pop(a).isVisible(),false);await a.locator('#reasoning-argument-mode').click();assert.equal(await a.locator('#reflection-body').inputValue(),'The availability estimate is the point we differ on.');assert.equal(await a.locator('#reflection-category').inputValue(),'facts');assert.equal(await a.locator('#compare-canvas .comparison-world').getAttribute('style'),camera);await action(a,'Save point');await pop(a).getByRole('button',{name:'Record my outcome',exact:true}).waitFor();const point=await byBody('The availability estimate is the point we differ on.');assert(point);assert.deepEqual(point.target,{type:'node',mapId:aMap.id,nodeId:ids['Quiet source without reasons']});assert.equal(await a.locator('.reasoning-card').count(),0);assert.match(await pop(a).innerText(),/Recorded by Alice/);for(const name of ['Reply','Respond','Challenge','Mark resolved','Accept challenge'])assert.equal(await pop(a).getByRole('button',{name,exact:true}).count(),0);
  await action(a,'Record my outcome');await a.locator('#reflection-body').fill('I need representative evidence before changing this estimate.');await pop(a).getByText('Outcome (optional)',{exact:true}).click();await a.locator('#reflection-category').selectOption('more_work');await a.locator('#reflection-next-step').fill('Survey members who have not replied.');await action(a,'Save my outcome');await pop(a).getByRole('button',{name:'Back to point of disagreement',exact:true}).waitFor();const aliceOutcome=await byBody('I need representative evidence before changing this estimate.');assert.equal(aliceOutcome.authorId,alice.id);assert.deepEqual(aliceOutcome.target,{type:'entry',entryId:point.id});
  await load(b);await b.locator('#reasoning-argument-mode').click();await find(b,point.body);assert.match(await pop(b).innerText(),/Recorded by Alice/);assert.equal(await pop(b).getByRole('button',{name:'Edit',exact:true}).count(),0);await action(b,'Record my outcome');await b.locator('#reflection-body').fill('I understand why we interpret the estimate differently.');await pop(b).getByText('Outcome (optional)',{exact:true}).click();await b.locator('#reflection-category').selectOption('difference_understood');await action(b,'Save my outcome');await pop(b).getByRole('button',{name:'Back to point of disagreement',exact:true}).waitFor();await action(b,'Back to point of disagreement');assert.match(await pop(b).innerText(),/Outcome · Alice[\s\S]*More work needed/);assert.match(await pop(b).innerText(),/Outcome · Bob[\s\S]*Difference understood/);assert.equal((await records()).filter(r=>isReflectionOutcome(r)&&r.target.entryId===point.id).length,2);assert.equal(await pop(b).getByRole('button',{name:'Edit my outcome',exact:true}).count(),1);assert(!/Both agree|Agreement reached|Resolved by/.test(await pop(b).innerText()));
  await action(b,'Edit my outcome');await b.locator('#reflection-body').fill('I changed my estimate after the new explanation.');await pop(b).getByText('Outcome (optional)',{exact:true}).click();await b.locator('#reflection-category').selectOption('changed_position');await action(b,'Save changes');await pop(b).getByRole('button',{name:'Back to point of disagreement',exact:true}).waitFor();const bobOutcome=await byBody('I changed my estimate after the new explanation.');assert.equal(bobOutcome.version,2);assert.equal(bobOutcome.history[0].reflection.result,'difference_understood');assert.deepEqual((await records()).find(r=>r.id===aliceOutcome.id),aliceOutcome);assert.equal(challengeState(await records(),challenge),'Open','Individual outcomes do not resolve challenges');
  await close(b);await b.getByRole('button',{name:'Conversations',exact:true}).click();const group=pop(b).locator(`.reflection-conversation[data-point="${point.id}"]`);assert.match(await group.innerText(),/Alice[\s\S]*representative evidence[\s\S]*Survey members[\s\S]*Bob[\s\S]*changed my estimate/);assert.equal(await group.locator('.reflection-assessment').count(),2);assert.equal(await pop(b).locator(`[data-entry="${aliceOutcome.id}"]`).count(),1);await b.screenshot({path:'build/design-review/grouped-outcomes-desktop.png',fullPage:true});await b.setViewportSize({width:390,height:844});await b.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await b.screenshot({path:'build/design-review/grouped-outcomes-mobile.png',fullPage:true});await b.setViewportSize({width:1440,height:1000});await find(b,bobOutcome.body);
  await b.screenshot({path:'build/design-review/reflection-outcome-desktop.png',fullPage:true});await b.setViewportSize({width:390,height:844});await b.waitForFunction(()=>{const r=document.querySelector('.discussion-popover').getBoundingClientRect();return document.documentElement.scrollWidth<=innerWidth&&r.left>=0&&r.right<=innerWidth+1;});await b.screenshot({path:'build/design-review/reflection-outcome-mobile.png',fullPage:true});await b.setViewportSize({width:1440,height:1000});

  // Statements, inferences and map edges keep distinct attachment targets.
  await follow(a);await card(a,child.id);const statement=await submitPoint(a,'We differ on whether eighteen replies are enough.',{category:'facts'});assert.deepEqual(statement.target,{type:'entry',entryId:child.id});await card(a,reason.id);await action(a,'Inspect reasoning connection');const inference=await submitPoint(a,'We differ on whether the sample supports this conclusion.',{category:'reasoning'});assert.deepEqual(inference.target,{type:'inference',entryId:reason.id});await noAnnotationCards(a);
  await find(a,'Survey members who have not replied');assert.match(await pop(a).innerText(),/I need representative evidence/);await noAnnotationCards(a);
  await follow(a);await close(a);await a.locator(`.reasoning-card[data-entry="${reason.id}"] .reasoning-fold`).first().click();assert.equal(await a.locator(`.reasoning-card[data-entry="${child.id}"]`).count(),0);await find(a,statement.body);assert.equal(await a.locator(`.reasoning-card[data-entry="${child.id}"]`).count(),1,'Finding a point reveals its actual reason through folds');assert.match(await pop(a).innerText(),/eighteen replies/);await noAnnotationCards(a);
  await close(a);await a.locator('.comparison-view-options>summary').click();for(const side of ['a','b'])await a.locator('#compare-collapse-'+side).click();await a.locator('.comparison-view-options>summary').click();assert(await a.locator('.node .reflection-marker').count(),'Collapsed source branches retain their disagreement count');await a.locator('#reasoning-compare-mode').click();assert.equal(await a.locator('.reflection-marker,.reasoning-card').count(),0,'Compare hides argument annotations');await a.locator('#reasoning-argument-mode').click();await find(a,inference.body);assert.match(await pop(a).innerText(),/Reasoning connection: Most respondents/);await noAnnotationCards(a);await expand(a);await close(a);
  const edge=a.locator('.discussion-edge-hit:not(.discussion-relationship-hit)').first();await edge.focus();await a.keyboard.press('Enter');const edgePoint=await submitPoint(a,'This map connection leaves an assumption unstated.');assert.equal(edgePoint.target.type,'edge');
  assert.deepEqual((await view(store,alice)).workspace.maps,originalMaps,'Questions, points and outcomes leave both source maps unchanged');assert.deepEqual((await records()).find(r=>r.id===challenge.id),challenge);assert.equal((await records()).filter(r=>r.kind==='relationship').length,0);

  // An acknowledgment lost after commit is recovered without a duplicate even
  // after the source changes; unsent source changes require explicit review.
  await node(a,'Nested source');await submitPoint(a,'Retry my saved point without duplication.',{retry:true});await pop(a).getByRole('alert').filter({hasText:'acknowledgment was lost'}).waitFor();const retry=await byBody('Retry my saved point without duplication.'),beforeRetry=writes.length;await edit(store,alice,ws=>{const map=ws.maps.find(m=>m.id===aMap.id);map.nodes.find(n=>n.id===ids['Nested source']).summary='The author changed this source after the acknowledgment was lost.';map.revision++;synchronizeIdeas(ws,map);});await action(a,'Save point');await pop(a).getByRole('button',{name:'Record my outcome',exact:true}).waitFor();assert.equal(writes.length,beforeRetry);assert.equal((await records()).filter(r=>r.body===retry.body).length,1);assert.equal((await byBody(retry.body)).sourceSnapshots[0].wording.summary,'Original source explanation for Nested source');
  await node(a,'Nested source');await action(a,'Mark point of disagreement');await a.locator('#reflection-body').fill('Preserve this unsaved point during source review.');await edit(store,alice,ws=>{const map=ws.maps.find(m=>m.id===aMap.id);map.nodes.find(n=>n.id===ids['Nested source']).summary='Another source edit while the annotation is open.';map.revision++;synchronizeIdeas(ws,map);});await action(a,'Save point');await pop(a).getByRole('button',{name:'I reviewed the updated source',exact:true}).waitFor();assert.equal(await a.locator('#reflection-body').inputValue(),'Preserve this unsaved point during source review.');assert.equal(await byBody('Preserve this unsaved point during source review.'),undefined);await action(a,'I reviewed the updated source');await action(a,'Save point');await pop(a).getByRole('button',{name:'Record my outcome',exact:true}).waitFor();assert.equal((await byBody('Preserve this unsaved point during source review.')).sourceSnapshots[0].wording.summary,'Another source edit while the annotation is open.');
  // A previously changed source is explicitly reviewed even when Edit opens later.
  await find(a,retry.body);await action(a,'Edit');await a.locator('#reflection-body').fill('My revised point after reviewing its changed source.');await action(a,'Save changes');await pop(a).getByRole('button',{name:'I reviewed the updated source',exact:true}).waitFor();assert.match(await pop(a).innerText(),/Previously reviewed[\s\S]*Original source explanation for Nested source[\s\S]*Current source[\s\S]*Another source edit/);await action(a,'I reviewed the updated source');await action(a,'Save changes');await pop(a).getByRole('button',{name:'Record my outcome',exact:true}).waitFor();const revised=await byBody('My revised point after reviewing its changed source.');assert.equal(revised.id,retry.id);assert.equal(revised.reviewedSources[0].wording.summary,'Another source edit while the annotation is open.');assert.equal(await pop(a).locator('.review-warning').count(),0,'Explicit source review is recorded, not merely acknowledged in the form');
  // When an uncertain request was not committed, retry its original identity
  // before applying any text the author edited while waiting.
  await node(a,'Nested source');await action(a,'Mark point of disagreement');await a.locator('#reflection-body').fill('Original uncertain draft.');failBeforeNext=true;await action(a,'Save point');await pop(a).getByRole('alert').filter({hasText:'not been acknowledged'}).waitFor();const uncertainId=uncertain.at(-1).find(c=>isReflection(c.value)).id;await a.locator('#reflection-body').fill('Edited while the original save was uncertain.');await action(a,'Save point');await pop(a).getByRole('button',{name:'Record my outcome',exact:true}).waitFor();const recovered=await byBody('Edited while the original save was uncertain.');assert.equal(recovered.id,uncertainId);assert.equal(recovered.version,2);assert.equal(recovered.history[0].body,'Original uncertain draft.');assert.equal((await records()).filter(r=>r.id===uncertainId).length,1);
  // A definite stale-source rejection clears the batch, retaining its ID so
  // review can recover without endlessly resubmitting the rejected wording.
  await node(a,'Nested source');await action(a,'Mark point of disagreement');await a.locator('#reflection-body').fill('Uncertain draft before a source change.');failBeforeNext=true;await action(a,'Save point');await pop(a).getByRole('alert').filter({hasText:'not been acknowledged'}).waitFor();const staleId=uncertain.at(-1).find(c=>isReflection(c.value)).id;await edit(store,alice,ws=>{const map=ws.maps.find(m=>m.id===aMap.id);map.nodes.find(n=>n.id===ids['Nested source']).summary='Source changed before uncertain write was committed.';map.revision++;synchronizeIdeas(ws,map);});await action(a,'Save point');await pop(a).getByRole('alert').filter({hasText:/source changed|source.*withdrawn/i}).waitFor();await action(a,'Save point');await pop(a).getByRole('button',{name:'I reviewed the updated source',exact:true}).waitFor();await action(a,'I reviewed the updated source');await action(a,'Save point');await pop(a).getByRole('button',{name:'Record my outcome',exact:true}).waitFor();assert.equal((await byBody('Uncertain draft before a source change.')).id,staleId);
  await find(a,inference.body);await action(a,'Record my outcome');await a.locator('#reflection-body').fill('Keep my concurrent outcome draft.');await a.locator('#reflection-next-step').fill('Keep this proposed next step.');raceNextOutcome=true;await action(a,'Save my outcome');await pop(a).getByRole('alert').filter({hasText:'already have an outcome'}).waitFor();assert.equal(await a.locator('#reflection-body').inputValue(),'Keep my concurrent outcome draft.');assert.equal(await a.locator('#reflection-next-step').inputValue(),'Keep this proposed next step.');assert.equal((await records()).filter(r=>isReflectionOutcome(r)&&r.authorId===alice.id&&r.target.entryId===inference.id).length,1);a.once('dialog',d=>d.accept());await close(a);
  await load(b);await b.locator('#reasoning-argument-mode').click();await find(b,revised.body);await edit(store,alice,ws=>{ws.maps.find(m=>m.id===aMap.id).visibility='private';});await b.getByRole('button',{name:'Refresh',exact:true}).click();await b.waitForFunction(()=>!document.querySelector('.reflection-marker')&&!document.querySelector('.reasoning-card'));assert.equal((await view(store,bob)).workspace.discussions.filter(isReflection).length,0,'Access loss removes annotation data');assert(!(await b.locator('body').innerText()).includes(revised.body));
  assert.deepEqual(errors,[]);console.log('Reflection browser passed: editable Compare preset, two-account attributed outcomes, separate statement/inference targets, attached markers, folds/search, draft/source review, retry identity, mobile and privacy.');
}catch(error){for(const [i,ctx]of browser.contexts().entries())for(const p of ctx.pages()){await p.screenshot({path:`build/design-review/reflection-failure-${i}.png`,fullPage:true});console.error((await p.locator('body').innerText()).slice(-6500));}console.error(errors);throw error;}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}


