import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {handleAPI} from '../worker/api.mjs';
import {initialWorkspace} from '../dist/workspace.mjs';
import {endorseNodes} from '../dist/adoption.mjs';
const sqlite=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sqlite.exec(readFileSync(`drizzle/${file}`,'utf8'));
const DB={prepare(sql){return {bind(...args){return {async first(){return sqlite.prepare(sql).get(...args)||null;}};}};}};
const get=()=>handleAPI(new Request('https://harmonious.test/api/workspace'),{DB});
const put=(workspace,expectedRevision,origin='https://harmonious.test')=>handleAPI(new Request('https://harmonious.test/api/workspace',{method:'PUT',headers:{'content-type':'application/json',origin},body:JSON.stringify({workspace,expectedRevision})}),{DB});
let response=await get();assert.deepEqual(await response.json(),{revision:0,workspace:null,updatedAt:null});
const workspace=initialWorkspace(),[person,,reference]=workspace.maps;endorseNodes(workspace,{participantId:person.ownerId,sourceMapId:reference.id,nodeIds:[reference.nodes.find(n=>n.parent!==null).id],targetMapId:person.id});response=await put(workspace,0);assert.equal(response.status,200);assert.equal((await response.json()).revision,1);
assert.deepEqual((await (await get()).json()).workspace,workspace,'Reopening restores both maps');
assert.equal((await put(workspace,0)).status,409,'A second session cannot overwrite a newer save');
workspace.maps[0].name='Renamed saved map';response=await put(workspace,1);assert.equal(response.status,200);assert.equal((await response.json()).revision,2);
assert.equal((await put(workspace,1)).status,409);assert.equal((await (await get()).json()).workspace.maps[0].name,'Renamed saved map');
assert.equal((await put(workspace,2,'https://another.test')).status,403);
assert.equal((await put({schemaVersion:99},2)).status,400);
assert.equal((await handleAPI(new Request('https://harmonious.test/api/workspace',{method:'DELETE'}),{DB})).status,405);
assert.equal((await handleAPI(new Request('https://harmonious.test/api/workspace',{method:'PUT',headers:{'content-type':'application/json'},body:'x'.repeat(2_000_001)}),{DB})).status,413);
assert.equal((await (await get()).json()).revision,2,'Rejected requests do not change saved data');
sqlite.close();console.log('PASS: real SQLite migration, save/reopen, optimistic revision conflict, invalid input rejection, origin checks, payload limit, and preservation of saved data after rejected writes.');
