import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {clientAssets} from '../scripts/client-assets.mjs';
import {AccountAuth} from '../worker/account-auth.mjs';
import {handleAccountAPI} from '../worker/account-api.mjs';
import {memoryStore} from './accounts.test.mjs';
const owner={id:'11111111-1111-4111-8111-111111111111',email:'owner@example.test',email_confirmed_at:'2026-09-29',user_metadata:{display_name:'Organizer'}},users=new Map([[owner.id,owner]]),passwords=new Map(),sessions=new Map(),store=memoryStore(),errors=[];
let env,creates=0;
const authFetch=async(url,options)=>{
 const path=new URL(url).pathname.replace('/auth/v1/',''),body=options.body?JSON.parse(options.body):null;
 const session=user=>{const token=crypto.randomUUID();sessions.set(token,user);return Response.json({user,access_token:token,refresh_token:token,expires_in:3600});};
 if(path==='admin/users'&&options.method==='POST'){if([...users.values()].some(u=>u.email===body.email))return Response.json({code:'email_exists'},{status:422});const user={...body,id:crypto.randomUUID(),email_confirmed_at:'2026-09-29'};passwords.set(user.id,body.password);delete user.password;users.set(user.id,user);creates++;return Response.json(user);}
 if(path==='admin/users')return Response.json({users:[...users.values()]});
 if(path.startsWith('admin/users/')){const user=users.get(path.split('/').at(-1));if(options.method==='PUT')passwords.set(user.id,body.password);return Response.json(user);}
 if(path==='otp')return Response.json({});
 if(path==='verify')return session(owner);
 if(path==='token'){if(body.refresh_token)return session(sessions.get(body.refresh_token));const user=[...users.values()].find(u=>u.email===body.email);return user&&passwords.get(user.id)===body.password?session(user):Response.json({},{status:400});}
 if(path==='user'){const user=sessions.get(options.headers.authorization?.replace('Bearer ',''));return Response.json(user||{},{status:user?200:401});}
 return Response.json({});
};
const assets=await clientAssets(),server=createServer(async(req,res)=>{try{const url=new URL(req.url,env.APP_ORIGIN);if(url.pathname.startsWith('/api/')){let raw='';for await(const chunk of req)raw+=chunk;const request=new Request(url,{method:req.method,headers:req.headers,...(raw?{body:raw}: {})}),response=await handleAccountAPI(request,env,{auth:new AccountAuth(env,authFetch),store});res.writeHead(response.status,{...Object.fromEntries(response.headers),'set-cookie':response.headers.getSetCookie()});res.end(await response.text());return;}const asset=assets[url.pathname];res.writeHead(asset?200:404,{'content-type':asset?.type||'text/plain'});res.end(asset?.body||'Not found');}catch(error){errors.push(error.message);res.writeHead(500);res.end('Test server error');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;env={APP_ORIGIN:origin,SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public',SUPABASE_SECRET_KEY:'sb_secret_private',SIGNUP_MODE:'public',TEST_ACCOUNT_ADMIN_ID:owner.id};
const {chromium}=await import(pathToFileURL(process.env.HARMONIOUS_PLAYWRIGHT)),browser=await chromium.launch({headless:true,channel:process.env.HARMONIOUS_BROWSER||'msedge'});
try{
 await mkdir('build/design-review',{recursive:true});const organizer=await browser.newPage({viewport:{width:1400,height:1000}}),tester=await browser.newPage();for(const page of [organizer,tester]){page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));}
 await organizer.goto(origin);await organizer.locator('#account-name').fill('Organizer');await organizer.locator('#account-email').fill(owner.email);await organizer.getByRole('button',{name:'Email me a sign-in code',exact:true}).click();await organizer.locator('#account-code').fill('123456');await organizer.getByRole('button',{name:'Sign in',exact:true}).click();await organizer.locator('#account-display').getByText('Organizer',{exact:true}).waitFor();
 await organizer.locator('.account-menu > summary').click();await organizer.getByRole('button',{name:'Test accounts',exact:true}).click();const modal=organizer.getByRole('dialog',{name:'Test accounts'});await modal.getByText('No test accounts yet.',{exact:true}).waitFor();
 await modal.getByLabel('Display name',{exact:true}).fill('Pilot One');await modal.getByLabel('Username',{exact:true}).fill('pilot01');await modal.getByRole('button',{name:'Create test account',exact:true}).click();await modal.getByText('Ready to share with this tester.',{exact:true}).waitFor();assert.equal(creates,1);
 const credentials=await modal.getByLabel('Test account login details').inputValue(),password=credentials.match(/Password: (.+)/)[1];assert.match(credentials,/Username: pilot01/);assert.match(credentials,/Use a test account/);assert(!credentials.includes('email'));await organizer.screenshot({path:'build/design-review/test-accounts-admin.png'});
 await tester.goto(origin);await tester.getByRole('button',{name:'Use a test account',exact:true}).click();assert.equal(await tester.locator('#account-email-form').isVisible(),false);await tester.getByLabel('Test username',{exact:true}).fill('PILOT01');await tester.getByLabel('Password',{exact:true}).fill('wrong');await tester.getByRole('button',{name:'Sign in with test account'}).click();await tester.getByText('The test username or password is incorrect.',{exact:true}).waitFor();
 await tester.getByLabel('Password',{exact:true}).fill(password);await tester.getByRole('button',{name:'Sign in with test account'}).click();await tester.locator('#account-display').getByText('Pilot One',{exact:true}).waitFor();await tester.reload();await tester.locator('#account-display').getByText('Pilot One',{exact:true}).waitFor();await tester.locator('.account-menu > summary').click();assert.equal(await tester.getByRole('button',{name:'Test accounts',exact:true}).isVisible(),false);assert.equal((await tester.request.get(origin+'/api/admin/test-accounts')).status(),403);
 await tester.getByRole('button',{name:'Sign out',exact:true}).click();await tester.getByRole('button',{name:'Use a test account',exact:true}).waitFor();
 organizer.once('dialog',d=>d.accept());await modal.getByRole('button',{name:'Reset password',exact:true}).click();await modal.getByText('Ready to share with this tester.',{exact:true}).waitFor();const replacement=(await modal.getByLabel('Test account login details').inputValue()).match(/Password: (.+)/)[1];assert.notEqual(replacement,password);
 await tester.getByRole('button',{name:'Use a test account',exact:true}).click();await tester.getByLabel('Test username',{exact:true}).fill('pilot01');await tester.getByLabel('Password',{exact:true}).fill(password);await tester.getByRole('button',{name:'Sign in with test account'}).click();await tester.getByText('The test username or password is incorrect.',{exact:true}).waitFor();await tester.getByLabel('Password',{exact:true}).fill(replacement);await tester.getByRole('button',{name:'Sign in with test account'}).click();await tester.locator('#account-display').getByText('Pilot One',{exact:true}).waitFor();
 await organizer.setViewportSize({width:390,height:844});await organizer.screenshot({path:'build/design-review/test-accounts-narrow.png'});assert(await organizer.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));organizer.once('dialog',d=>d.accept());await modal.getByRole('button',{name:'Close',exact:true}).click();assert.equal(await organizer.getByLabel('Test account login details').inputValue(),'');
 assert.equal(creates,1);assert.deepEqual(errors,[]);console.log('Test accounts browser: organizer creation, login without email, wrong credentials, reload, owner boundaries, password replacement, credential clearing and narrow screens passed.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
