import assert from 'node:assert/strict';
import {initialWorkspace,validateWorkspace,createMap,recordComparison,comparisonHealth} from '../dist/workspace.mjs';
import {synchronizeIdeas} from '../dist/adoption.mjs';
const w=initialWorkspace(),[a,b]=w.maps;validateWorkspace(w);
assert.notEqual(a.id,b.id);const blank=createMap('New person','Pat');assert.equal(blank.nodes.length,3);assert.equal(blank.relations.length,0);
const input={aMapId:a.id,bMapId:b.id,aNodeId:'a211',bNodeId:'a211',questionStatus:'matched',question:'Should question comparison precede answer comparison?',answerStatus:'divergent',notes:'Explore the different starting points.'};
const record=recordComparison(w,input);assert(record.provisional);w.comparisons.push(record);validateWorkspace(w);assert(!comparisonHealth(w,record).needsReview);
assert.throws(()=>recordComparison(w,{...input,bMapId:a.id}),/different maps/);
assert.throws(()=>recordComparison(w,{...input,questionStatus:'incommensurable'}),/requires an established shared question/);
assert.throws(()=>recordComparison(w,{...input,aNodeId:null,answerStatus:'aligned'}),/missing response/);
assert.throws(()=>recordComparison(w,{...input,question:''}),/Write the shared question/);
const initialSummary=record.aSnapshot.node.summary;a.nodes.find(n=>n.id==='a211').summary='An edited position.';a.revision++;synchronizeIdeas(w,a);
assert.equal(record.aSnapshot.node.summary,initialSummary);assert.deepEqual(comparisonHealth(w,record).changed,['a']);
const updated=recordComparison(w,{...input,answerStatus:'partial'},record);assert.equal(updated.history.length,1);assert.equal(updated.history[0].aSnapshot.node.summary,initialSummary);assert.equal(updated.id,record.id);assert(!comparisonHealth(w,updated).needsReview);
w.comparisons=[updated];const reopened=validateWorkspace(JSON.parse(JSON.stringify(w)));assert.deepEqual(reopened,w);assert(!comparisonHealth(reopened,updated).needsReview);
a.nodes=a.nodes.filter(n=>n.id!=='a211');assert.deepEqual(comparisonHealth(w,updated).missing,['a']);validateWorkspace(w);
const absence=recordComparison(w,{...input,aNodeId:'a1',bNodeId:null,answerStatus:'asymmetric'});assert(!comparisonHealth(w,absence).needsReview);b.revision++;assert.deepEqual(comparisonHealth(w,absence).changed,['b']);
assert.throws(()=>validateWorkspace({...w,maps:[a,{...b,id:a.id}]}),/duplicate/);
assert.throws(()=>validateWorkspace({...w,comparisons:[{...updated,history:[null]}]}),/history/);
console.log('PASS: separate maps, question-before-answer validation, provisional divergences, portable round trip, preserved snapshots, source-change and deletion flags, and reviewed comparison history.');
