import {readFile,mkdir,writeFile,cp} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
const clientFiles=['index.html','style.css','layout.mjs','data.mjs','model.mjs','account-model.mjs','account-ui.mjs','adoption.mjs','workspace.mjs','comparison-layout.mjs','compare-canvas.mjs','participation-ui.mjs','workspace-ui.mjs','app.mjs'];
const assets={};for(const file of clientFiles){assets[`/${file}`]={body:await readFile(`dist/${file}`,'utf8'),type:file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8'};}assets['/']=assets['/index.html'];
const parts=[];for(const path of ['dist/account-model.mjs','dist/layout.mjs','dist/model.mjs','dist/data.mjs','dist/adoption.mjs','dist/workspace.mjs','db/store.mjs','worker/api.mjs'])parts.push((await readFile(path,'utf8')).replace(/^import .*?;\n/gm,'').replace(/^export /gm,''));
const output=parts.join('\n')+`\nconst siteAssets=${JSON.stringify(assets)};\nexport default {async fetch(request,env){const pathname=new URL(request.url).pathname;if(pathname.startsWith('/api/'))return handleAPI(request,env);const asset=siteAssets[pathname];if(!asset)return new Response('Not found',{status:404});if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});return new Response(request.method==='HEAD'?null:asset.body,{headers:{'content-type':asset.type,'cache-control':'no-cache','x-content-type-options':'nosniff'}});}};\n`;
execFileSync('node',['--check','--input-type=module'],{input:output});
await mkdir('dist/server',{recursive:true});await writeFile('dist/server/index.js',output);
await mkdir('dist/.openai',{recursive:true});await cp('.openai/hosting.json','dist/.openai/hosting.json');await cp('drizzle','dist/.openai/drizzle',{recursive:true});
console.log('Worker, frontend assets, and database migrations built.');
